### ISSUE TITLE
Some examples in the README don't seem to work.

### ISSUE THREAD

**Issue by noshbar** [elevenlabs/elevenlabs-python#1]
First off, really appreciate this project, thank you!

Steps I took:
1. I created an Anaconda environment with `Python 3.10.9` on Windows 10
2. I installed via `pip install elevenlabs`
3. I tried running the first simplest example and got `ModuleNotFoundError: No module named 'IPython'`
4. I installed IPython with `pip install ipython`
5. I created a `.py` file containing the first example
6. Trying the first example, the only output of the program is: `<IPython.lib.display.Audio object>` on the commandline
7. The same happens for the "Voices" sample
8. However, the "Streaming" sample DOES work!

So perhaps noting that IPython needs to be installed would be good.
And I'm not terribly sure what's happening with the other samples.

Thanks again, and let me know if I can be more useful.

**Comment by flavioschneider** [comment]
Hi! Thanks for the detailed feedback. I added `ipython` as a required dependency. The `play` function provided was thought for python notebooks, but I updated it to play with ffmpeg so now should work everywhere. You can alternatively use the `save(audio, 'myfile.wav')` function to save the audio.

**Comment by noshbar** [comment]
That's some speedy work there!
I had looked at the API documentation to see if `play` was intended for console or not, but it's not been filled out yet, so I figured it _might_ be something like that.

But I just updated, and the samples work great now, thank you so much!

**Comment by flavioschneider** [comment]
No problem! Updated the API doc with those utility functions as well.

**Comment by noshbar** [comment]
Awesome stuff, I really look forward to giving this a proper try tomorrow.

I'll leave you to close the issue and get that juicy satisfaction from it!
