### ISSUE TITLE
🐞 bug in Italian when it comes to reading numbers

### ISSUE THREAD

**Issue by fylls** [elevenlabs/elevenlabs-python#101]
here's an example `valuta la tua esperienza da 1 a 10`
11labs speaks perfect Italian but then, out of the blue, it reads the numbers in English;

essentially, it's reading this;
`valuta la tua esperienza da ONE a TEN`

instead of this:
`valuta la tua esperienza da UNO a DIECI`

code:
```python
        # generate audio
        audio = elevenlabs.generate(
            text=message,
            voice="Rachel",
            model="eleven_multilingual_v1",
        )

```

**Comment by flavioschneider** [comment]
We are aware of this issue, a temporary hack to fix this is to convert numbers into words (1=uno, 10=dieci).

**Comment by flavioschneider** [comment]
Closing as similar to #83
