### ISSUE TITLE
Error when trying to access User info 

### ISSUE THREAD

**Issue by HectorBertucat** [elevenlabs/elevenlabs-python#11]
Hi everyone !

When trying to get user information, I get this error :

`ValidationError: 1 validation error for User
subscription -> available_models
  field required (type=value_error.missing)`

I did 

`from elevenlabs import generate, set_api_key
from elevenlabs.api import User
set_api_key(config.get('api', 'key'))
user = User.from_api()
print(user)`

This does not work in Google Collab either.

I imported the correct library, I set the API key but when trying to get User info, there is an error.

**Comment by flavioschneider** [comment]
Hi @HectorBertucat! This has been fixed in `v0.2.9` (`pip install elevenlabs -U` to update) thanks for reporting!

**Comment by HectorBertucat** [comment]
Thank you !
