### ISSUE TITLE
Python API vs REST API

### ISSUE THREAD

**Issue by oliverw** [elevenlabs/elevenlabs-python#111]
The Python API currently does not support ..

- PCM Sound Data
- Projects

The latter is quite new of course but it would be nice if there would be feature parity in the not too distant future.

**Comment by cmann50** [comment]
As a workaround, you can add a monkey patch to your file and add the parameter to convert to pcm_16000 to the URL.

```python
# BEGIN MONKEY PATCH
 
from typing import Iterator, Optional  # Monkey patch
from elevenlabs import TTS  # Monkey patch
from elevenlabs.api.model import Model  # Monkey patch
from elevenlabs.api.base import API, api_base_url_v1  # Monkey patch


def my_generate_stream(
        text: str,
        voice: Voice,
        model: Model,
        stream_chunk_size: int = 2048,
        api_key: Optional[str] = None,
        latency: int = 1,
) -> Iterator[bytes]:
    url = f"{api_base_url_v1}/text-to-speech/{voice.voice_id}/stream?optimize_streaming_latency={latency}&output_format=pcm_16000"
    print("Monkey patch URL: " + url)
    data = dict(
        text=text,
        model_id=model.model_id,
        voice_settings=voice.settings.model_dump() if voice.settings else None,
    )  # type: ignore
    response = API.post(url, json=data, stream=True, api_key=api_key)
    for chunk in response.iter_content(chunk_size=stream_chunk_size):
        if chunk:
            yield chunk


TTS.generate_stream = my_generate_stream  # Monkey patch
# END MONKEY PATCH
```

This works flawlessly for real-time audio streaming to Twilio for me, whereas before trying to convert the mp3 was glitchy and threw errors (probably because of it's variable rate). 

If I change latency to 4, the quality is still really good, and it starts the reply in about 1-1.5 seconds for my use case.

**Comment by oliverw** [comment]
> As a workaround, you can add a monkey patch to your file and add the parameter to convert to pcm_16000 to the URL.
> 
> ```python
> # BEGIN MONKEY PATCH
>  
> from typing import Iterator, Optional  # Monkey patch
> from elevenlabs import TTS  # Monkey patch
> from elevenlabs.api.model import Model  # Monkey patch
> from elevenlabs.api.base import API, api_base_url_v1  # Monkey patch
> 
> 
> def my_generate_stream(
>         text: str,
>         voice: Voice,
>         model: Model,
>         stream_chunk_size: int = 2048,
>         api_key: Optional[str] = None,
>         latency: int = 1,
> ) -> Iterator[bytes]:
>     url = f"{api_base_url_v1}/text-to-speech/{voice.voice_id}/stream?optimize_streaming_latency={latency}&output_format=pcm_16000"
>     print("Monkey patch URL: " + url)
>     data = dict(
>         text=text,
>         model_id=model.model_id,
>         voice_settings=voice.settings.model_dump() if voice.settings else None,
>     )  # type: ignore
>     response = API.post(url, json=data, stream=True, api_key=api_key)
>     for chunk in response.iter_content(chunk_size=stream_chunk_size):
>         if chunk:
>             yield chunk
> 
> 
> TTS.generate_stream = my_generate_stream  # Monkey patch
> # END MONKEY PATCH
> ```
> 
> This works flawlessly for real-time audio streaming to Twilio for me, whereas before trying to convert the mp3 was glitchy and threw errors (probably because of it's variable rate).
> 
> If I change latency to 4, the quality is still really good, and it starts the reply in about 1-1.5 seconds for my use case.

Interesting workaround. Will try that but this should really be in the official version.

**Comment by Mbamin** [comment]
> As a workaround, you can add a monkey patch to your file and add the parameter to convert to pcm_16000 to the URL.
> 
> ```python
> # BEGIN MONKEY PATCH
>  
> from typing import Iterator, Optional  # Monkey patch
> from elevenlabs import TTS  # Monkey patch
> from elevenlabs.api.model import Model  # Monkey patch
> from elevenlabs.api.base import API, api_base_url_v1  # Monkey patch
> 
> 
> def my_generate_stream(
>         text: str,
>         voice: Voice,
>         model: Model,
>         stream_chunk_size: int = 2048,
>         api_key: Optional[str] = None,
>         latency: int = 1,
> ) -> Iterator[bytes]:
>     url = f"{api_base_url_v1}/text-to-speech/{voice.voice_id}/stream?optimize_streaming_latency={latency}&output_format=pcm_16000"
>     print("Monkey patch URL: " + url)
>     data = dict(
>         text=text,
>         model_id=model.model_id,
>         voice_settings=voice.settings.model_dump() if voice.settings else None,
>     )  # type: ignore
>     response = API.post(url, json=data, stream=True, api_key=api_key)
>     for chunk in response.iter_content(chunk_size=stream_chunk_size):
>         if chunk:
>             yield chunk
> 
> 
> TTS.generate_stream = my_generate_stream  # Monkey patch
> # END MONKEY PATCH
> ```
> 
> This works flawlessly for real-time audio streaming to Twilio for me, whereas before trying to convert the mp3 was glitchy and threw errors (probably because of it's variable rate).
> 
> If I change latency to 4, the quality is still really good, and it starts the reply in about 1-1.5 seconds for my use case.

Hey @cmann50 thanks for workaround. 

I'm trying to integrate this into Twilio myself but I'm having some issues setting up the bidrectional streams. Would you mind sharing some code on how you got elevenlabs integrated with Twilio? That would be much appreciated!

**Comment by cmann50** [comment]
I posted my code here.  This worked pretty well and streamed the audio with good quality and minor delay.  We decided not to use elevenlabs since it was too expensive for our use case - polly neural was priced better, and openai recently released a similarly prices TTS.

https://github.com/cmann50/twilio-elevenlabs-lambda-demo/tree/cmann50-patch-1

**Comment by Mbamin** [comment]
Thanks so much! This helped me out a ton ! 

I've also been debating moving away from ElevenLabs due to their pricing, I'll take a look at both Polly and OpenAI's new TTS.

**Comment by dsinghvi** [comment]
Hey @oliverw -- ElevenLab's SDK is now automatically generated from an OpenAPI spec. You can see all the resources that are in the SDK ([link](https://github.com/elevenlabs/elevenlabs-python/tree/main/src/elevenlabs/resources)) which includes `projects`, `models`, `voices`, etc. 

See the README for downloading the latest SDK and feel free to re-open this issue if you encounter any problems.
