### ISSUE TITLE
ImportError: cannot import name 'voices' from partially initialized module 'elevenlabs' (most likely due to a circular import)

### ISSUE THREAD

**Issue by qiuyuzhao** [elevenlabs/elevenlabs-python#112]
ImportError: cannot import name 'voices' from partially initialized module 'elevenlabs' (most likely due to a circular import)

**Comment by moonClimber** [comment]
Same issue here

> ImportError: cannot import name 'voices' from partially initialized module 'elevenlabs' (most likely due to a circular import)

**Comment by mohajit2711** [comment]
Similar issue with generate.

**Comment by gradiently** [comment]
Same issue here elevenlabs==0.2.26
