### ISSUE TITLE
Unable to stream text to speech on Safari

### ISSUE THREAD

**Issue by ben5556** [elevenlabs/elevenlabs-python#113]
Unable to stream text to speech on Safari. It shows an error (screenshot attached)

<img width="1437" alt="image" src="https://github.com/elevenlabs/elevenlabs-python/assets/39107453/1d5cc089-91f6-444a-92ea-f1a98aabe08a">

Works as expected on Chrome and Firefox. Using the sample Python code provided. Is this occurring because of the `Range` header on Safari which starts off with `Range: bytes=0-1`. ? I don't see your API accepting range parameter to be able to handle this. Any help is appreciated

```
import requests

CHUNK_SIZE = 1024
url = "https://api.elevenlabs.io/v1/text-to-speech/<voice-id>/stream"

headers = {
  "Accept": "audio/mpeg",
  "Content-Type": "application/json",
  "xi-api-key": "<xi-api-key>"
}

data = {
  "text": "Hi! My name is Bella, nice to meet you!",
  "model_id": "eleven_monolingual_v1",
  "voice_settings": {
    "stability": 0.5,
    "similarity_boost": 0.5
  }
}

response = requests.post(url, json=data, headers=headers, stream=True)
```

**Comment by TasseDeCafe** [comment]
The solution to this is to send an empty bytes string for the first API call that Safari does, inside your endpoint:

```    def send_empty_bytes_string():
        # Send an empty audio file to tell Safari that this the response is bytes
        partial_content = b""  # A very small part of the beginning of the audio stream
        headers = {"Content-Range": "bytes 0-1/*"}
        return Response(
            partial_content, status_code=206, media_type="audio/mpeg", headers=headers
        )

    # Handling the 'Range' header
    if range and "bytes=0-1" in range:
        return send_empty_bytes_string()
```

**Comment by dsinghvi** [comment]
Closing -- thanks for resolving the issue @TasseDeCafe!
