### ISSUE TITLE
Stream Stuttering with "eleven_multilingual_v2" model

### ISSUE THREAD

**Issue by Munkyfoot** [elevenlabs/elevenlabs-python#114]
I have been using the `stream` method with the default model without any issues, but when I switched to the "eleven_multilingual_v2" model I started noticing stuttering in the audio playback. I tried adjusting the `latency` and `stream_chunk_size` to various values, but it only seemed to make it worse. Anyone else experience this?

**Comment by JonathanChavezTamales** [comment]
According to [their docs](https://docs.elevenlabs.io/api-reference/text-to-speech-websockets):
> "Input streaming is currently not supported with Eleven Multilingual v2. We aim to enable it in the coming days."

Underneath the stream function there are multiple websocket calls done in series and the text is tokenized so each word has an api call.

The playback choppiness is because there is no buffer and the data is not coming as fast as the clips are played.

A workaround is to override the `stream` function to add a buffer to the stream, but this will introduce a delay at the beginning. 

Another method is to split up the original text by sentences (dots or commas), make websocket calls concurrently and then merging the results preserving the order. This is more tricky to implement because dealing with iterators and concurrent calls is difficult, but the results would be amazing: near 0 latency + continuous streaming.

**Comment by 1030** [comment]
Can anybody confirm if this is supposed to be fixed? I still experience the stuttering although the above message is now omitted from the docs.

**Comment by RicardoEscobar** [comment]
[VIDEO: Elevenlabs stuttering using eleven_multilingual_v2](https://www.youtube.com/watch?v=HmLyc2V6RvA)
I explained what I found but I was corrected on my assumptions by [lugia19 on discord](https://discord.com/channels/1066739690436313158/1179962239508299776/1180826823928598558):
```
This is a good theory, but it's actually incorrect
let me explain
each chunk is not an mp3 file in in of itself
the reason why audio data is missing is that you're saving them as if they were separate mp3 files
which leads to VLC skipping over the bytes it expects to contain the mp3 header
but since the chunks are all simply part of the same, overarching mp3 file, there are no headers (besides in the very first chunk)
so it's skipping actual audio data
(just so you know, the input streaming does account for this, both in the official elevenlabs library and my own, so this is indeed not the source of the problem)
I'm currently working on a rework of how my own library handles the websocket streaming, I'll have you test it once that's finished
```

**Comment by RicardoEscobar** [comment]
[VIDEO: [Progress on the stuttering issue with elevenlabs multilingual v2](https://studio.youtube.com/video/_u11qjQi7ZM/edit)](https://youtu.be/_u11qjQi7ZM)

The video covers how to mitigate stuttering by using the `stream()` function and not trying to playback or save the chunks individually. Also I think the audio format from the elevenlabs response is an mp3 file with 44.1khz sample width.
At the end of the video I cover a new issue regarding the audio volume  degrading on long lasting audio stream responses from the API.

**Comment by RicardoEscobar** [comment]
[VIDEO: Stutter issue with example code](https://www.youtube.com/watch?v=5WNdetux8OA)
I made an example script to replicate the stutter issue:
```python
"""
This module replicates the stuttering issue with weleven labs stream mode.
"""
import os

import openai
import elevenlabs
import dotenv


def load():
    """take environment variables from .env."""
    dotenv.load_dotenv()

    # Create an OpenAI client
    client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    # Set the Eleven API key
    elevenlabs.set_api_key(os.getenv("ELEVENLABS_API_KEY"))

    # Load the path where the mpv player is located.
    # This is used to play the audio with elevenlabs.stream()
    os.environ["PATH"] += os.pathsep + os.getenv("MPV_PATH")

    return client

def text_stream(prompt: str, client: openai.OpenAI, print_output: bool = True):
    """Yield text from the OpenAI stream as it arrives"""

    # Prompt for the user to say something
    openai_stream = client.chat.completions.create(
        model="gpt-4-1106-preview",
        messages=[{"role": "user", "content": prompt}],
        stream=True,
    )

    for chunk in openai_stream:
        if chunk.choices[0].delta.content is not None:
            if print_output:
                print(chunk.choices[0].delta.content, end="")
            yield chunk.choices[0].delta.content


if __name__ == "__main__":
    # Get OpenAi client
    client = load()

    # Create a voice, if you have issues with the voice_id, check the documentation or use this line instead:
    # voice = "Nicole"
    voice = elevenlabs.Voice(voice_id="chQ8GR2cY20KeFjeSaXI")

    user_prompt = "Summarize the \"Little Red Riding Hood\" story in Spanish."

    # Stream audio in real-time, as it's being generated.
    audio_stream = elevenlabs.generate(
        text=text_stream(user_prompt, client),
        voice=voice,
        model="eleven_multilingual_v2",
        stream=True
    )

    # Play the audio stream
    elevenlabs.stream(audio_stream)
```
Here is the [GitHub repo for the code](https://github.com/RicardoEscobar/elevenlabs-stutter)

**Comment by tecoad** [comment]
I have this exactly same issue with eleven_multilingual_v2 @Munkyfoot, were you able to mitigate it?

Regards

**Comment by sibbl** [comment]
The problem still persists. Maybe the multilingual turbo model will fix it, but so far there's no details about the model's availability nor this stuttering issue for the non-turbo model.

**Comment by abiel-lozano** [comment]
A workaround I found in the discord server is to switch to the `eleven_multilingual_v1` model. Seems like the only way to generate a stable audio stream in other languages right now.
