### ISSUE TITLE
pydantic issues

### ISSUE THREAD

**Issue by mcantillon21** [elevenlabs/elevenlabs-python#117]
I keep getting this issue: PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify 
`skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with 
`@model_validator`.

Name: elevenlabs
Version: 0.2.26
Name: pydantic
Version: 2.4.2

Any idea what to do??

**Comment by notnotdurgesh** [comment]
Instead of `pip install elevenlabs` try this `pip install git+https://github.com/elevenlabs/elevenlabs-python.git`.
it worked for me. i guess they fixed in the repo but not in pip

**Comment by dsinghvi** [comment]
@mcantillon21 @notnotdurgesh ElevenLabs now uses [Fern](https://buildwithfern.com/) to generate their SDKs. We have just published an beta version `v0.3.0b0` that is both Pydantic V1 and V2 compatible so you should no longer see this error. 

If you still see pydantic issues, feel free to re-open this issue!
