### ISSUE TITLE
saving audio files?

### ISSUE THREAD

**Issue by AdWY21** [elevenlabs/elevenlabs-python#12]
I asked a question here: https://stackoverflow.com/questions/76163192/elevenlabs-python-how-to-set-a-storage-path-for-the-output-mpv-audio-files

I can't specify path to save audio files ,

**Comment by flavioschneider** [comment]
Play is only to reproduce the audio, you can use the `save` function if you want to save it instead:

```py
from elevenlabs import generate, save

audio = generate(
  text="Hi! My name is Bella, nice to meet you!",
  voice="Bella",
  model="eleven_monolingual_v1"
)

save(audio, "speech.mp3")
```
