### ISSUE TITLE
Issue: Error During Video Dubbing After Creating an Account

### ISSUE THREAD

**Issue by ashudevcodes** [elevenlabs/elevenlabs-python#123]
## Issue Description

I am trying to dub a 6-minute video on ElevenLabs, but I am getting an error that says "Unusual activity detected. Free Tier usage disabled." I am not using a proxy or VPN, and I have not created multiple free accounts.

## Error Message

<img src="https://github.com/elevenlabs/elevenlabs-python/assets/105356967/4a4a09e1-70b8-454c-8d5d-cc73e6e10332" width="400" height="600">

## Steps to Reproduce

1. Go to the ElevenLabs website and create an account.
2. Click on the `Dubbing` option.
3. Click on `Create new Dub`.
4. Choose `YouTube` option.
6. Paste the URL of the video you want to dub.
7. Click on the `Create` button.

## Expected Behavior

Expected to successfully dub the entire 6-minute video after creating an account.

## Actual Behavior

An error message is displayed: "Unusual activity detected. Free Tier usage disabled."

## Environment

- Browser: Firefox version 118.0.1

## Screenshots/Logs
![image](https://github.com/elevenlabs/elevenlabs-python/assets/105356967/25b69ca0-0a59-44bb-9831-cd8e3922e4b5)

<img src="https://github.com/elevenlabs/elevenlabs-python/assets/105356967/39a42542-b0d7-4e6f-8b60-593ae3099c9a" width="400" height="600">

## Note

The video link is [https://www.youtube.com/watch?v=r6tH55syq0o&t=5s](https://www.youtube.com/watch?v=r6tH55syq0o&t=5s). The goal is to resolve the error and successfully dub the entire 6-minute video.

**Comment by MohamedNoordin** [comment]
Maybe this is related to the fact that dubs do use 2000 characters per minute of audio? 6 minutes × 2000 characters = 12000 characters. That exceeds the limit of 10000 characters per month for the free tier. You need to subscribe for the creator tier or at least for the starter tier. You can view the different tiers at https://elevenlabs.io/subscription.
