### ISSUE TITLE
Error in line 51 of base.py 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by RichardBoreiko** [elevenlabs/elevenlabs-python#125]
First, the error (using pretty-errors):

base.py 51 request
message = detail.get("message", "")

AttributeError:
'list' object has no attribute 'get'

And the code:

```
import elevenlabs
import pretty_errors

voice = elevenlabs.Voice(
    # voice_id="ZQe5CZNOzWyzPSCn5a3c",  # James
    voice_id='CYw3kZ02Hs0563khs1Fj',  # Dave
    settings=elevenlabs.VoiceSettings(
        stability=0,
        similarity_boost=0.75
    )
)

audio = elevenlabs.generate(
    text="Hi, my name is Dave!",
    voice=voice
)

elevenlabs.play(audio)
elevenlabs.save(audio, "audio_Dave.mp3")

```

**Comment by MichaelBicker** [comment]
It seems ElevenLabs code contains code within the following file that will only accept a list (not a dictionary)

In base.py:

`message = detail.get("message", "")`

----> This could be changed to this:

```
if isinstance(detail, list):
    message = detail[0] if detail else ""
else:
    message = detail.get("message", "")
```


This will test if "detail" is indeed a list, if not it accesses it as a dictionary.

**Comment by ibehnam** [comment]
Weird that this hasn't been addressed yet. My quota finished because I kept trying to fix this issue...

**Comment by rajtilakjee** [comment]
Any updates on this? I am facing the same issue.

**Comment by rajtilakjee** [comment]
@RichardBoreiko in case youhaven't found a solution to this, try updating the ElevenLabs Python library to the latest version. In case you have done that already, include the following parameters in the `generate` function: `style`, `use_speaker_boost`.

**Comment by RichardBoreiko** [comment]
> @RichardBoreiko in case youhaven't found a solution to this, try updating the ElevenLabs Python library to the latest version. In case you have done that already, include the following parameters in the `generate` function: `style`, `use_speaker_boost`.

It's working now, although I didn't change the parameters. Thanks!
