### ISSUE TITLE
Control over dubbed audio duration

### ISSUE THREAD

**Issue by DiogoVidevince** [elevenlabs/elevenlabs-python#128]
I am trying to dub a 5-minute long audio based on a subtitle (.vtt) file transcribed using Whisper. This file provides the duration of each sentence, and I aim to dub the content sentence by sentence. However, each sentence, once dubbed, tends to be "faster" than expected. For example, a 5-second sentence might be reduced to just 3 seconds in the dubbed version. When I combine all the audio clips for the video, there are noticeable and awkward pauses between sentences.

I've also tried dubbing the entire audio in one go, merging all the sentences, but this approach results in a 5-minute audio being condensed into just 3 minutes and 30 seconds.

Is there a way to define or control the duration of the output in the dubbing process?

**Comment by alasokolova** [comment]
@DiogoBerna Hey, have you solved this issue?
