### ISSUE TITLE
Key error "usecase" and "use case"

### ISSUE THREAD

**Issue by xinghua-qu** [elevenlabs/elevenlabs-python#129]
{'accent': 'american', 'description': 'childlish', 'age': 'young', 'gender': 'female', 'use case': 'animation'}
Gigi american young animation
{'accent': 'american', 'age': 'young', 'gender': 'female', 'description ': 'overhyped', 'usecase': 'video games'}

Kindly align the key about "use case".

**Comment by yacine-bens** [comment]
Description key also has a whitespace at the end for voice "Freya" and "Grace" : `"description "`
