### ISSUE TITLE
RateLimitError:  can I get an audio for 900 characters with my API key?

### ISSUE THREAD

**Issue by AdWY21** [elevenlabs/elevenlabs-python#13]
````
RateLimitError: This request exceeds your quota. You have 119 characters remaining, while 965 characters are required for this request.
````

**Comment by flavioschneider** [comment]
The free quota includes 10k characters in total. If you want to increase your quota, you can upgrade your plan on the website [https://beta.elevenlabs.io/pricing](https://beta.elevenlabs.io/pricing)

**Comment by AdWY21** [comment]
I think elevenlabs needs to solve few issues like saving audios and reading long text without (robot like sounds) before asking users to upgrade , its like planning a wedding for a first date .. google_speech seems to be better despite the voice quality .. I can easily save audios to any destination, and no upgrade required

**Comment by flavioschneider** [comment]
Saving audio files is possible with the `save` function, see https://github.com/elevenlabs/elevenlabs-python/issues/12#issuecomment-1533015377. Reading long text is also supported. Thanks for the feedback.
