### ISSUE TITLE
use of <break time="0.5s" /> in python api call

### ISSUE THREAD

**Issue by sascham** [elevenlabs/elevenlabs-python#131]
Hi, 
I'm sure it has an simple solution, i can't find it in the api description on how to use items like <break time="0.5s" /> 

thanks

**Comment by DiogoVidevince** [comment]
@sascham I don't think this is implemented on this lib, unfortunately.

The only solution I was able to use was the `-` | `--` | `---` intervals. Like:

"This is a test. --- Not the best one."
