### ISSUE TITLE
AttributeError: partially initialized module 'elevenlabs' has no attribute 'generate' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mohajit2711** [elevenlabs/elevenlabs-python#135]
This is my code:
import elevenlabs
audio = elevenlabs.generate(
    text = "Hi, I'm from the future!",
    voice = "Bella"
)
 
elevenlabs.play(audio)
elevenlabs.save(audio, "audio.mp3")

This is my error:
    audio = elevenlabs.generate(
            ^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'elevenlabs' has no attribute 'generate' (most likely due to a circular import)

**Comment by Podidiving** [comment]
:wave:

my guess is you named your script `elevenlabs.py`. You should rename it

**Comment by dsinghvi** [comment]
Closing this issue since the workaround suggest works!
