### ISSUE TITLE
can not use rate and pitch for Voice ?

### ISSUE THREAD

**Issue by sihaixuan** [elevenlabs/elevenlabs-python#139]
this code is from website doc Introduction:
`from elevenlabs import VoiceSettings  
  
settings = VoiceSettings(speaking_rate=0.8)  
audio = generate("Welcome to our podcast!", voice="Amy", settings=settings)
`
However,actually it can not use!

**Comment by Jitendra2603** [comment]
Incorrect docs, no such parameters yet.

**Comment by dsinghvi** [comment]
This is fixed in the latest SDK (`v1.0.0b0`). Please reopen if the issue still persists!
