### ISSUE TITLE
audio speed contorl already?

### ISSUE THREAD

**Issue by ThetaRgo** [elevenlabs/elevenlabs-python#146]
how to control audio speed,it too fast for me.

**Comment by Jitendra2603** [comment]
No speed parameter yet, you would have to use some 3rd party software to slow it down, you can also try reducing the stability and increasing similarity to see if that helps.

**Comment by dsinghvi** [comment]
Closing this issue since this is not a Python SDK issue and a general API request for the ElevenLabs team.

**Comment by firattamurlc** [comment]
Why there is not any implementation or feature about this ???
