### ISSUE TITLE
Is speech to speech being added to the API?

### ISSUE THREAD

**Issue by shealan** [elevenlabs/elevenlabs-python#147]
This is the feature I have been waiting for. I'd love to access this feature via the API.

Is this on the roadmap? If so, any eta?

**Comment by Jitendra2603** [comment]
Definitely on the roadmap, unfortunately, no ETA.

**Comment by dsinghvi** [comment]
This is now available in the latest SDK `v1.0.0b1`. Please install and provide any feedback you may have!
