### ISSUE TITLE
scalablity on parallel request 

### ISSUE THREAD

**Issue by santhosh-sp** [elevenlabs/elevenlabs-python#150]
Hello Team,

Please share the scalability on concurrent request with streaming? And Its their limitations too....

Thanks,
Santhosh

**Comment by Jitendra2603** [comment]
https://help.elevenlabs.io/hc/en-us/articles/14312733311761-How-many-requests-can-I-make-and-can-I-increase-it-

**Comment by dsinghvi** [comment]
Closing as completed.
