### ISSUE TITLE
How to get audio duration?

### ISSUE THREAD

**Issue by dumitruPuggle** [elevenlabs/elevenlabs-python#153]
```py
audio = generate(
    text=response,
    model="eleven_multilingual_v2",
    voice=Voice(
        voice_id=Var.CHATBOT_ELEVENLABS_VOICE_ID,
        settings=VoiceSettings(
            stability=stability,
            similarity_boost=similarity_boost,
            use_speaker_boost=True  # type: ignore
        )
    )
)
```

Is there any way to receive the full body response with audio duration along with audio bytes?

**Comment by Jitendra2603** [comment]
The response headers do not include the duration of the audio, you would have to work with some approximation, unfortunately.

$$\text{Duration (in seconds)} = \frac{\text{Size (in bytes)} \times 8}{\text{Bitrate (in kbps)}}$$

ElevenLabs delivers audio in the MP3 format with a bitrate of 128kbps for the Free and Starter plans, and 192kbps for the Creator, Independent Publisher, and Growing Business plans.

**Comment by dsinghvi** [comment]
Closing this issue since it is unsupported in the API (and won't be available in the Python SDK) for the foreseeable future.
