### ISSUE TITLE
APIError: User not found, it is likely still being created.

### ISSUE THREAD

**Issue by Aliraqimustafa** [elevenlabs/elevenlabs-python#156]
---------------------------------------------------------------------------
APIError                                  Traceback (most recent call last)
[<ipython-input-29-9f6870027573>](https://localhost:8080/#) in <cell line: 3>()
      1 from elevenlabs import generate, play
      2 
----> 3 audio = generate(
      4   text="Hello! 你好! Hola! नमस्ते! Bonjour! こんにちは! مرحبا! 안녕하세요! Ciao! Cześć! Привіт! வணக்கம்!",
      5   voice="Bella",

3 frames
[/usr/local/lib/python3.10/dist-packages/elevenlabs/api/base.py](https://localhost:8080/#) in request(url, method, api_key, **kwargs)
     69                 raise AuthorizationError(message)
     70 
---> 71         raise APIError(message, status)
     72 
     73     @staticmethod

APIError: User not found, it is likely still being created.

**Comment by Jitendra2603** [comment]
This was a Firebase issue, basically, you would have to retry creating the account and use the new API key.

**Comment by dsinghvi** [comment]
Closing this issue since it is a user issue (not an SDK issue).
