### ISSUE TITLE
Instant clone performance degradation

### ISSUE THREAD

**Issue by GordonDongZHAO** [elevenlabs/elevenlabs-python#157]
I am very satisfied with the effect of the instant clone on November 7th, so I upgraded my subscription. 
But when I used it again today, I found that the effect had become worse. The model (11.7 instant clone), same settings, the results are very different. Mandarin Chinese has become non-standard and full of strange flavor
[11labs_chinese_1107vs1218.zip](https://github.com/elevenlabs/elevenlabs-python/files/13699188/11labs_chinese_1107vs1218.zip)

**Comment by Jitendra2603** [comment]
Make sure you are passing the same settings and model 
```
from elevenlabs import Voice, VoiceSettings, generate

audio = generate(
    text="Hello! My name is Bella.",
    model="eleven_multilingual_v2",
    voice=Voice(
        voice_id='EXAVITQu4vr4xnSDxMaL',
        settings=VoiceSettings(stability=0.71, similarity_boost=0.5, style=0.0, use_speaker_boost=True)
    )
)

play(audio)
```

**Comment by dsinghvi** [comment]
@GordonDongZHAO closing this issue, please re-open if the work around of passing the `VoiceSettings` did not work!
