### ISSUE TITLE
Stop streaming

### ISSUE THREAD

**Issue by rodriheck** [elevenlabs/elevenlabs-python#158]
Let's say I have a setup like this:

```
audio_stream = generate(
    text=text_stream(),
    voice="Charlie",
    model="eleven_turbo_v2",
    latency=4,
    stream=True,
    output_format="ulaw_8000",
)

for chunk in audio_stream:
    break
```

It appears that if I run it again soon after it breaks, it takes around 10s for generate() to start again, which suggests that the previous run is somehow blocking my next run. I read that theoretically we have ~3 concurrent calls we can make, but that doesn't seem to be the case, since this mere example is enough to make the next run clog. Is it possible to break my previous streaming? Then I would be able to do the next one right away.

**Comment by nafets33** [comment]
I recall reading that when streaming if your text doesn't end with an ending  '.',  '?',  '!', ...etc then the stream doesn't break

**Comment by dsinghvi** [comment]
That is correct (see here for the full [list](https://github.com/elevenlabs/elevenlabs-python/blob/bfc3a97389090c12e737bceca3e0ac6aada5d062/src/elevenlabs/realtime_tts.py#L22-L38))
