### ISSUE TITLE
End of stream error

### ISSUE THREAD

**Issue by sb1992** [elevenlabs/elevenlabs-python#167]
Sending eos to 11labs...

Error from 11labs: {"message":"Could not parse input message, make sure it is a json and follows the schema outlined in protocol.","error":"invalid_input_message","code":1008}
 
 My EOS is 
```await ws.send(json.dumps({"text": ""})) ```

**Comment by dsinghvi** [comment]
Hey @sb1992 -- can you try using the `client.text_to_speech.convert_realtime()` method instead of directly communicating with the socket? This should solve your problem.
