### ISSUE TITLE
[BUG/UI] Overflowing text in sidebar on Desktop

### ISSUE THREAD

**Issue by mischulz14** [elevenlabs/elevenlabs-python#171]
Disclaimer: I know this is the API repo, but maybe this gets put through to the FrontendDevs (:

### Description
When I go to elevenlabs.io and look at my profile in the sidebar, my email-address text overflows the button. 
<img width="405" alt="Screenshot 2024-01-26 at 12 38 49" src="https://github.com/elevenlabs/elevenlabs-python/assets/96014669/f0dfe14f-9b1d-444c-a895-006b4b8416b6">

Just wanted to let you guys know, I don't know anywhere else to post this issue

### Technical Details
I recently read that this is a common issue in flex containers and css in general and can usually be fixed by setting `min-width: 0` for the element.

**Comment by 11hemendra** [comment]
Thanks! @mischulz14  I'm on it🫡

**Comment by 11hemendra** [comment]
Done https://github.com/elevenlabs/xi/pull/1364

@mischulz14 You can create issues here https://github.com/elevenlabs/issues/issues

**Comment by mischulz14** [comment]
> Done https://github.com/elevenlabs/xi/pull/1364
> 
> @mischulz14 You can create issues here https://github.com/elevenlabs/issues/issues

I think I am not authorized to do this. I get the 404 page for your pull request and the other link you sent 
<img width="1173" alt="Screenshot 2024-01-26 at 13 54 52" src="https://github.com/elevenlabs/elevenlabs-python/assets/96014669/770e2ac3-2d2e-433b-b8bb-6b78985adca4">

**Comment by dsinghvi** [comment]
@mischulz14 closing this issue since we are hoping to keep the issues to the Python SDK! If you still have problems using the UI, feel free to reopen!
