### ISSUE TITLE
python api ,clone error: You cannot upload the same file twice

### ISSUE THREAD

**Issue by iraymondking** [elevenlabs/elevenlabs-python#172]
` set_api_key("xxxxx")
        voice = clone(
            name=name,
            description="An old  male voice with a slight hoarseness in his throat.",
            # Optional
            files=files,
        )`

the "files" is :['./voice_cache/65af751e190125609327d02c/1706253073020.mp3', './voice_cache/65af751e190125609327d02c/1706253097426.mp3', './
voice_cache/65af751e190125609327d02c/1706253113904.mp3', './voice_cache/65af751e190125609327d02c/1706253664188.mp3'] 

the error in console: Error: You cannot upload the same file twice. 
Does anyone used this api?

**Comment by dsinghvi** [comment]
@iraymondking The `clone` API does not allow you to upload the same file multiple times. Can you just try uploading the file once? If that doesn't work, feel free to reopen this issue!

**Comment by SaudMohammad** [comment]
I had made a clone of my voice using 3 recording files and it was successfully created. so then I deleted the cloned voice from my elevenlabs acccount and tried re-creating it using same 3 recordings, but it generated an error: APIError: You cannot upload the same file twice.

**Comment by rizhangdev** [comment]
FWIW I'm experiencing this same problem... I don't think OP uploaded the file multiple times. When I try to upload multiple files at the same time, it give me the "duplicate_files" error even though they are definitely not duplicated.
