### ISSUE TITLE
elevenlabs.client

### ISSUE THREAD

**Issue by wealthypotato** [elevenlabs/elevenlabs-python#173]
Hello, i am having issues find the matching distribution for elevenlabs.client. i have tried using pip install elevenlabs.client with no luck. i am currently running python 3.11 with a pip version of 23.3. any help would be greatly appreciated thanks

**Comment by dsinghvi** [comment]
@wealthypotato @n45os apologize for any inconvenience. The installation instructions have been [updated](https://github.com/elevenlabs/elevenlabs-python?tab=readme-ov-file#%EF%B8%8F-install)!
