### ISSUE TITLE
SSML tags processing bug

### ISSUE THREAD

**Issue by matyushinleonid** [elevenlabs/elevenlabs-python#175]
I want to add a pause to the speech. According to [this article](https://help.elevenlabs.io/hc/en-us/articles/13416374683665-How-can-I-add-pauses) one may use ssml tag `break`. The problem is that it does not work if I add a closing tag to the request. 

Namely, when I send a request with the following text (with a closing tag), there is no pause.
```python
'Hello <break time="2s"></break> world'
```

However, if I use a self-closing tag (like in example in the article), it works just fine.
```python
'Hello <break time="2s"/> world'
```

The first case should be supported on your side as well, since it is completely identical to the second one from XML perspective.

**Comment by BrokenSkull1** [comment]
It happens to me also when ever I tried to add intonations. It never
Generate Audio with intonations

**Comment by dsinghvi** [comment]
Hey thanks for submitting the issue! Since there is a workaround that works, I'll be closing this for now!
