### ISSUE TITLE
TTS Usage

### ISSUE THREAD

**Issue by DDGC7** [elevenlabs/elevenlabs-python#177]
from elevenlabs.client import ElevenLabs
from elevenlabs import generate, play
import os

client = ElevenLabs(api_key=my api key)
folder_path = my folder path
text_filename = 'input_text.txt'
audio_filename = 'output_audio.mp3'

text_file_path = os.path.join(folder_path, text_filename)
audio_file_path = os.path.join(folder_path, audio_filename)

with open(text_file_path, 'r') as text_file:
    input_text = text_file.read()

audio = generate(
    text=input_text,
    voice="Adam",
    model="eleven_multilingual_v2"
)

play(audio)

with open(audio_file_path, "wb") as audio_file:
    audio_file.write(audio)

So this is my code right now and the usage used to be pretty simple. Now I am getting this error "UnauthenticatedRateLimitError: Thanks for trying out our speech synthesis! You have reached the limit of unauthenticated requests. You can continue, for free, by setting a valid API key." I have already put my API key yet I still get this. I read the updated documentation and I dont know how to use the "client" variable to make the text to speech work. Can someone help?

**Comment by dsinghvi** [comment]
@DDGC7 You'll need to pass your `api_key` into the generate  [function](https://github.com/elevenlabs/elevenlabs-python/blob/9cd495e9ff801f9726fe421ad1f27d9b85c22602/src/elevenlabs/generate.py#L26). 

Or you can set `ELEVEN_API_KEY`. If this doesn't work, feel free to open the GitHub issue again.
