### ISSUE TITLE
generate can't find the Voice ID of a previously registered voice

### ISSUE THREAD

**Issue by mor-panjaya** [elevenlabs/elevenlabs-python#179]
I have added a new voice via the python client api, and received a valid Voice_ID (I can also see the new voice at the web UI).
When I try to generate an audio using that Voice_ID I get the following error:
_**A voice for the voice_id <Voice_ID> was not found.**_

I get the error for every Voice_ID of a previously registered voice in my account.
When I try to generate with one of the given default voices (using its relevant Voice_ID) it works fine without any error.

The code to add the new voice:
`client = ElevenLabs(api_key=MY_API_KEY)`
`files = ["./file1.wav", "./file2.wav"]`
`add_voice_response = client.voices.add(`
`    name="name",`
`    description="description",`
`    files=[open(file, 'rb') for file in files],`
`    labels=str({}))`
`voice_id = add_voice_response.voice_id`

The code to generate the audio:
`voice = client.voices.get(voice_id=voice_id)`
`audio = generate(`  _--This command causes the error_
`    text="Hello! My name is Name.",`
`    voice=voice,`
`    model="eleven_multilingual_v2")`

I don't think it's a credentials problem since I've managed to register new voices into my account.
What am I missing?

Thanks in advance!

**Comment by LukeS26** [comment]
I had the same issue, I believe it's caused by the client not correctly setting the env variable of ELEVEN_API_KEY which generate has as the default argument for api_key. You can get around it by calling generate with the api_key argument passed in.

```
audio = generate(
      text=text,
      voice=voice,
      model="eleven_multilingual_v2",
      api_key=MY_API_KEY)
```

**Comment by mor-panjaya** [comment]
Thanks @LukeS26!
Passing the api_key argument to the generate call solved it.
