### ISSUE TITLE
ModuleNotFoundError: No module named 'elevenlabs.client'

### ISSUE THREAD

**Issue by pashpashpash** [elevenlabs/elevenlabs-python#180]
I recently installed elevenlabs
```
pip3 install elevenlabs==0.2.27
```
And it seems like it's still on v2? I don't have `client` anywhere in `elevenlabs`:
import elevenlabs
print(dir(elevenlabs))

['API', 'APIError', 'Accent', 'Age', 'AuthorizationError', 'BaseModel', 'ConfigDict', 'DEFAULT_VOICE', 'Dict', 'Enum', 'FeedbackItem', 'Field', 'Gender', 'History', 'HistoryItem', 'Iterator', 'List', 'Listable', 'Literal', 'Model', 'Models', 'Optional', 'OutputFormat', 'Path', 'RateLimitError', 'Sequence', 'Subscription', 'TTS', 'UnauthenticatedRateLimitError', 'UnauthorizedVoiceCloningError', 'Union', 'User', 'Voice', 'VoiceClone', 'VoiceDesign', 'VoiceSample', 'VoiceSettings', 'Voices', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'annotations', 'api', 'api_base_url_v1', 'base', 'base64', 'clone', 'connect', 'datetime', 'error', 'generate', 'get_api_key', 'history', 'is_installed', 'is_voice_id', 'json', 'model', 'model_validator', 'os', 'play', 're', 'requests', 'save', 'set_api_key', 'shutil', 'simple', 'stream', 'subprocess', 'text_chunker', 'tts', 'user', 'utils', 'voice', 'voices', 'websockets']

The documentation says that I should import the client like this:
`from elevenlabs.client import AsyncElevenLabs`

But that throws this error:
```
    from elevenlabs.client import AsyncElevenLabs
ModuleNotFoundError: No module named 'elevenlabs.client'
```

Why is this happening? How do I get the v3 version of the python package?

**Comment by MasterReach1** [comment]
It appears that the 0.3.0 version hasn't officially been released yet despite the README showing documentation for using it. Pip doesn't even recognize any version above the recent release.

**Comment by MasterReach1** [comment]
My fix was to manually install the package from the v3 branch. Here's the pip command:

pip install git+https://github.com/elevenlabs/elevenlabs-python@v3

**Comment by dsinghvi** [comment]
@MasterReach1 Thanks for filing this GitHub issue and sorry for any inconvenience with installing the SDK. The SDK is now published to pypi and the install instructions are in the README. 

I'll be closing this issue, but if you run into any problems, feel free to open it again.
