### ISSUE TITLE
trying to fetch voices and only premade are returned

### ISSUE THREAD

**Issue by doesitevenmatter** [elevenlabs/elevenlabs-python#183]
```python
from elevenlabs.client import ElevenLabs
from elevenlabs import voices
 
client = ElevenLabs(api_key=key)
 
 
# Fetch the list of voices
voices = voices()
for voice in voices:
    print(voice)
    print()
``` 
this code only returns premade voices, is there any way I can get the custom ones?

**Comment by dsinghvi** [comment]
@doesitevenmatter can you try access the voices from the client itself: 

```python
response = client.voices.get_all();
```

**Comment by doesitevenmatter** [comment]
@dsinghvi For some reason it does show it but I am unable to parse the data since I can't find anything in the documentation regarding the class GetVoicesResponseModel and looping the response and doing something like "voice.category" doesn't help, can you help me out in filtering by category? or directing me to document that can help me?

**Comment by dsinghvi** [comment]
https://github.com/elevenlabs/elevenlabs-python/blob/d0a1b62ed93f2d1a2260fde2a86cb990b4ae59cf/src/elevenlabs/types/get_voices_response_model.py#L16 you should be able to use command click / mypy to help you. There is a `voices` property which is an array of voices

**Comment by dsinghvi** [comment]
@doesitevenmatter closing this issue, if you still have issues feel free to re-open this issue.
