### ISSUE TITLE
Read.ME adjustment for clarity

### ISSUE THREAD

**Issue by UselessToolsWasTaken** [elevenlabs/elevenlabs-python#184]
Hey! Right at the start the documentation says the following line:

```Python
from elevenlabs.client import ElevenLabs

client = ElevenLabs(api_key="...")
```

If you were to just run the ```generate()``` function with the api key used as shown above, you will very quickly run into a 401 error.

Example: 

```Python
eleven = ElevenLabs(
    api_key="your api key here"  # Defaults to ELEVEN_API_KEY
)

recognizer = sr.Recognizer()
voices = voices()
audio = generate(text="Hello there! You're now talking to Luna. Say 'quit' to exit the conversation",
                 voice="Domi",
                 model="eleven_monolingual_v1"
                 )

play(audio)
```

Instead, the correct way to use your API key is this 

```Python
eleven = ElevenLabs(
    api_key="your api key here"  # Defaults to ELEVEN_API_KEY
)

recognizer = sr.Recognizer()
voices = voices()
audio = generate(api_key="your api key here",
                 text="Hello there! You're now talking to Luna. Say 'quit' to exit the conversation",
                 voice="Domi",
                 model="eleven_monolingual_v1"
                 )

play(audio)
```

Where you basically Add the API key to the generate() function. As far as I could tell this is not mentioned anywhere in the documentation, the only way I found it is by going through what variables generate() takes. If this could be somehow added for future people like me that'd be awesome! Thanks :).

**Comment by dsinghvi** [comment]
@UselessToolsWasTaken thanks for the feedback, the README has been updated in this [PR](https://github.com/elevenlabs/elevenlabs-python/pull/187). If the SDK exposed the `generate`, `clone` and `design` methods directly on the generated client, would that be preferable?

**Comment by UselessToolsWasTaken** [comment]
I think that might help, It'll streamline the process a bit, but I'll leave what you want the best practice to be to you guys 😄
