### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bryanhpchiang** [elevenlabs/elevenlabs-python#185]
Can you add examples on how to use the new client API -- there are virtually 0 examples right now

**Comment by dsinghvi** [comment]
@bryanhpchiang The SDK has embedded code samples, checkout an [example](https://github.com/elevenlabs/elevenlabs-python/blob/d0a1b62ed93f2d1a2260fde2a86cb990b4ae59cf/src/elevenlabs/resources/history/client.py#L98-L113). You can access these by following the code complete in your editor.

**Comment by bryanhpchiang** [comment]
Awesome thanks -- where are the code samples for TTS?

https://github.com/elevenlabs/elevenlabs-python/blob/d0a1b62ed93f2d1a2260fde2a86cb990b4ae59cf/src/elevenlabs/resources/text_to_speech/client.py#L158

I'm just using the legacy `generate` function for now

**Comment by dsinghvi** [comment]
Thanks for the specific @bryanhpchiang. For some context, ElevenLabs uses [Fern](https://buildwithfern.com/) to autogenerate and manage their SDKs. We've filed a [bug report ](https://github.com/fern-api/fern/issues/3016) and will let you know when the SDK is generated with request samples that use TTS. 

If you have any more feedback using the v3 SDK, let us know!

**Comment by dsinghvi** [comment]
@bryanhpchiang this is now fixed with our latest beta release `v1.0.0b0`. Please re-open the issue if you still have any problems!
