### ISSUE TITLE
incompatibility with httpx 0.13.3 which is used in googletrans and many other libraries.

### ISSUE THREAD

**Issue by nabilHaouam** [elevenlabs/elevenlabs-python#190]
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
elevenlabs 0.3.0b0 requires httpx>=0.21.2, but you have httpx 0.13.3 which is incompatible.`

in order to work with elevenlabs with other libraries, it needs to support legacy versions that are still commonly used in many libs out there.

**Comment by dsinghvi** [comment]
@nabilHaouam would it be possible for you to take the upgrade for httpx? Which library is pinning it to `0.13.3` ?

**Comment by nabilHaouam** [comment]
the library causing the problem is `googletrans` ,the project stopped in version `4.0.0rc1` and it is incompatible with newer versions of `httpx` .
for my specific case, I have someone who forked the `googletrans` project and made it compatible, [here](https://github.com/ShivangKakkar/googletrans) .
