### ISSUE TITLE
Arabic Language does not work with API

### ISSUE THREAD

**Issue by Adam-Tafran** [elevenlabs/elevenlabs-python#191]
Arabic works perfectly on the website, but not when using API with Python. the resulting voices sound like English pronunciation of the Arabic alphabet, with 0 understandability. 

...............................

# coding: utf-8

import elevenlabs

api_key = "mykey"
elevenlabs.set_api_key(api_key)

voice = elevenlabs.Voice(
    voice = "ZQe5CZNOzWyzPSCn5a3c", model="eleven_multilingual_v2",
    settings = elevenlabs.VoiceSettings(
        stability = 0.75,  # Adjusted for more stability
        similarity_boost = 0.5
                  
    )
)

arabic_text = "تكلم بالعربية"

# Generate audio
audio = elevenlabs.generate(text= arabic_text, voice=voice)

# Save audio
audio = elevenlabs.save(audio, "test3.mp3")

**Comment by dsinghvi** [comment]
@Adam-Tafran This will be fixed on https://github.com/elevenlabs/elevenlabs-python/pull/196

**Comment by dsinghvi** [comment]
@Adam-Tafran Please give this a try on the latest SDK (`v1.0.0b0`)
