### ISSUE TITLE
Dependency on pydantic>=2.5.0 for v0.3.0b

### ISSUE THREAD

**Issue by kormang** [elevenlabs/elevenlabs-python#193]
What is the reason fern generated library depends on pydantic<2.5.0 ?

It seems fern guys downgraded from 3 to 2.5 here: https://github.com/fern-api/python-sdk/commit/525694e0f1e5e2057d4d24bc5a399720d8e4cd29

I'll ask there too.
Now I have problems, because some of the libraries I use depend on pydantic>=2.5.0.
Can you do anything about it?

**Comment by dsinghvi** [comment]
@kormang This is being fixed here https://github.com/elevenlabs/elevenlabs-python/pull/196

**Comment by kormang** [comment]
Thanks. I'm eager to try it out and close the issue.

**Comment by dsinghvi** [comment]
@kormang This is fixed on the latest CLI `v1.0.0b0`! Please re-open if you have anymore issues.
