### ISSUE TITLE
How do I use the speech to speech API from the Python client?

### ISSUE THREAD

**Issue by vedantroy** [elevenlabs/elevenlabs-python#197]
I can use `generate` to do tts. How can I do sts?

**Comment by nawed2611** [comment]
This isn't live yet through the library

**Comment by dsinghvi** [comment]
@vedantroy this is now available in the latest SDK `v1.0.0b0`!

**Comment by vedantroy** [comment]
How do I do use the API?

**Comment by bemi127** [comment]
Do you have some example code for using STS with the latest SDK?
