### ISSUE TITLE
What is the purpose of setting chunk_length_schedule

### ISSUE THREAD

**Issue by neil-zhao** [elevenlabs/elevenlabs-python#198]
I set this property, such as "generation_config": {"chunk_length_schedule": [50]}, and the returned result remains unchanged

**Comment by dsinghvi** [comment]
https://github.com/elevenlabs/elevenlabs-python/blob/bfc3a97389090c12e737bceca3e0ac6aada5d062/src/elevenlabs/realtime_tts.py#L105-L107 This should only impact the streaming websocket and configures how much audio to return. Closing this out for now!
