### ISSUE TITLE
handling audio streaming from server

### ISSUE THREAD

**Issue by nawed2611** [elevenlabs/elevenlabs-python#201]
Is this the best way to respond with the stream of audio generated through 11labs?

```
def text_stream():
            yield text

        audio_stream = generate(
            text=text_stream(),
            voice=voice_id,
            model="eleven_multilingual_v2",
            stream=True
        )

        def generate_audio():
            for chunk in audio_stream:
                yield chunk

        return Response(generate_audio(), 200, content_type="audio/wav")
```

This doesn't actually return the audio chunk when i call the route instead it responds with the full audio when generation is completed
Pls would appreciate some help

**Comment by dsinghvi** [comment]
Hey @nawed2611, please consider using `StreamResponse` instead! https://fastapi.tiangolo.com/reference/responses/?h=streaming. 

Since this is not an SDK issue, I will be closing this out.
