### ISSUE TITLE
Controlling speed and pitch with v1

### ISSUE THREAD

**Issue by flavianh** [elevenlabs/elevenlabs-python#214]
Hi, I saw you were revamping the library, which seems to be going in a good direction!
However, looking at VoiceSettings, I see that the control for pitch and speaking rate are gone (contrary to what this [documentation page](https://elevenlabs.io/docs/api-reference/python-text-to-speech-guide#text-to-speech) says).
What's the status on this?
Thanks

**Comment by dsinghvi** [comment]
@flavianh thanks for pointing those out. It turns out that those docs are inaccurate. Can you open an issue on the docs repo instead?
