### ISSUE TITLE
Save function generates a corrupted file

### ISSUE THREAD

**Issue by TheCultist** [elevenlabs/elevenlabs-python#223]
As the title says, when I generate an audio and use the save function, the resulting file can't be reproduced by any media player (I tried latest versions of VLC and Media Player classic and also reinstalled all the codecs).
The audio is correctly generated by the API call because the play function reproduces it correctly. The issue seems to be only with the saving.
Here's my code

```
from elevenlabs import play, save
from elevenlabs.client import ElevenLabs
import os

os.environ['PATH'] += os.pathsep + 'PATH-TO-FFMPEG-BIN'

client = ElevenLabs(
  api_key="MY-API-KEY"
)

audio = client.generate(
  text="Hello!",
  voice="Rachel",
  model="eleven_multilingual_v2"
)
play(audio)
save(audio, "test.mp3")
```

I'm on Windows environment

**Comment by satouani** [comment]
try this 
`audio_bytes = b''.join(list(audio))
audio_segment = AudioSegment.from_file(BytesIO(audio_bytes), format="mp3")
audio_segment.export(dirOut, format="wav")`

**Comment by TheCultist** [comment]
That returns a

**Comment by TheCultist** [comment]
When running that instead of the save, ffmpeg returns an exception

`Exception has occurred: CouldntDecodeError`

when running the line

`audio_segment = AudioSegment.from_file(BytesIO(audio_bytes), format="mp3")`

**Comment by TheCultist** [comment]
> try this ![image](https://private-user-images.githubusercontent.com/79143838/316050962-6d71f59e-3c73-4e25-b625-e53edf8edde3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTk0MjQsIm5iZiI6MTcxMTExOTEyNCwicGF0aCI6Ii83OTE0MzgzOC8zMTYwNTA5NjItNmQ3MWY1OWUtM2M3My00ZTI1LWI2MjUtZTUzZWRmOGVkZGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDE0NTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNjgxNDk0MTE4MTBkNjY4NWM2MDg4NzNjZTM3N2Y2ZWYyZjczZTkwYzU4MDgwNDFkMDU1NDhlNjM0MTIwNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kobgMnGcVTxL1tFxFBrTR0mdIDs0L4EQizfJeNj3b1A)


When running that instead of the save, ffmpeg returns an exception

`Exception has occurred: CouldntDecodeError
`
when running the line

`audio_segment = AudioSegment.from_file(BytesIO(audio_bytes), format="mp3")
`

**Comment by TheCultist** [comment]
Managed to make it work. It seems that running "play" consumes the response so if I run "save" right after, the response is an empty file. By removing the "play" command, the save works correctly
