### ISSUE TITLE
LICENSE file was deleted

### ISSUE THREAD

**Issue by C0rn3j** [elevenlabs/elevenlabs-python#226]
The LICENSE file that @elliotwutingfeng added was removed by @applebym in #165 again, it's not mentioned anywhere in the long commit notes, I presume that was a mistake?

https://github.com/elevenlabs/elevenlabs-python/commits/87027740319e6ea303112f273fc7d0c89a5dc0d5/LICENSE

**Comment by dsinghvi** [comment]
@C0rn3j that's correct, we'll add this back shortly.
