### ISSUE TITLE
Code examples suggestions

### ISSUE THREAD

**Issue by u-m-i** [elevenlabs/elevenlabs-python#230]
### Basically...

To use correctly <code>play</code> method in Windows and in the simplest way possible, it's necessary to set the <code>use_ffmpeg=False</code> and to install <code>sounddevice</code>, <code>soundfile</code> and <code>numpy</code>, 

A code snippet:

```python
voice = Voice(
        voice_id = catalogue.voices[3].voice_id,
        settings = voice_settings
        )

audio_ = client.generate(
        text="This is a test for Windows 10 or any Windows",
        voice = voice)

# Test for windows
play(audio=audio_, use_ffmpeg=False)

```

So I propose to leave it on one comment in the README's examples that uses play, so it's easy and convenient for Windows users.

Also if it can be included into the dependencies of the package would be much easier

**Comment by dsinghvi** [comment]
@u-m-i checkout out this [website](https://elevenlabs.docs.buildwithfern.com/api-reference/text-to-speech/convert) for code samples with the SDK. If you run into issues, let me know!
