### ISSUE TITLE
`Client.generate` method may have overly-wide type

### ISSUE THREAD

**Issue by spencerwilson** [elevenlabs/elevenlabs-python#232]
I noticed the return type on this method: https://github.com/elevenlabs/elevenlabs-python/blob/145352e87d16b2cac786ac2e20c5e4485b5fd23e/src/elevenlabs/client.py#L132

Should it be a `Union`, or could it just be an `Iterator[bytes]`? Looking at the various branches out of the function, it seems like they're all `Iterator[bytes]`. To work around this, in my code I'm currently running
```python
result = cast(Iterator[bytes], client.generate(...))
```

and I'm wondering if I'm missing something with this. Thanks!

**Comment by dsinghvi** [comment]
@spencerwilson great call -- this is a manually maintained helper function, would you be up to submit a PR to update the return type! We'll release this as `2.1.0` :D
