### ISSUE TITLE
I want to clone my voice into elevenlabs available voice using API

### ISSUE THREAD

**Issue by ruhullahshaikh** [elevenlabs/elevenlabs-python#234]
I want to upload my personal voice and convert it into speech to speech like elevenlabs using API

**code for reference.**
```
from elevenlabs.client import ElevenLabs
from elevenlabs import play

client = ElevenLabs(
  api_key="", # Defaults to ELEVEN_API_KEY
)

voice = client.clone(
    audio = "my_voice.mp3"
)

audio = client.generate(text = voice, voice="Rachel", model="eleven_multilingual_v2") // voice may be Rachel, Adam and so on

play(audio)
```
basically my audio played in the voice of Rachel. 
Help appreciated.
Thank you!

**Comment by dsinghvi** [comment]
`audio = client.generate(text = voice, voice="Rachel", model="eleven_multilingual_v2")` 

@ruhullahshaikh if you read this snippet you can see that you are setting `text=voice` and you are passing `voice="Rachel"`. Try passing `voice=voice.voice_id` instead and better text!

**Comment by gsavvid** [comment]
@dsinghvi If I understood correctly, @ruhullahshaikh wants to do `speech-to-speech` and not `text-to-(custom)speech`. Is `speech-to-speech` supported by this python library?
