### ISSUE TITLE
Custom Audio Voice clone using elevenlabs API key

### ISSUE THREAD

**Issue by ruhullahshaikh** [elevenlabs/elevenlabs-python#239]
Hello, I want voice clone application on my custom audio data, can anyone provide me with the python code using ElevenLabs API key.
please refer the steps below.
step 1: Upload custom audio/path to custom audio
step 2:  Select the voice_id/voice from elevenlabs //like Adam, Rachel etc.
step 3: select the model
step 4: your custom audio file generated with the dubbing voice of Adam
step 5: Finish
 
Thank you!

**Comment by dsinghvi** [comment]
Please see the README for how to do so! https://github.com/elevenlabs/elevenlabs-python?tab=readme-ov-file#clone-voice

**Comment by ruhullahshaikh** [comment]
`audio = client.generate(text="Hi! I'm a cloned voice!", voice=voice)`

brother I want audio file instead of text.

`audio = client.generate(file = audio.mp3, voice=voice)` // for reference may be code like this 


I want correct code for voice dubbing.

Thank you!
