### ISSUE TITLE
Add ability to return bytes object of streamed audio from stream()

### ISSUE THREAD

**Issue by Agent-R-QT** [elevenlabs/elevenlabs-python#24]
If there is a way to achieve this already, apologies in advance.
My recommendation would be to, as the chunks are processed in stream, construct a bytes object of the values. And then to return it at the end of this. Currently have an implementation of the Python wrapper that uses this function and needs to save it. For our codebase we have a modified version of the stream function that achieves this akin to updating stream to something like:

```
def stream(audio_stream: Iterator[bytes]) -> None:
    if not is_installed("mpv"):
        raise ValueError("mpv not found, necessary to stream audio.")

    mpv_command = ["mpv", "--no-cache", "--no-terminal", "--", "fd://0"]
    mpv_process = subprocess.Popen(
        mpv_command,
        stdin=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    bytes = b"" #Initialise bytes
    for chunk in audio_stream:
        if chunk is not None:
            mpv_process.stdin.write(chunk)  # type: ignore
            mpv_process.stdin.flush()  # type: ignore
            bytes += chunk #Update bytes

    if mpv_process.stdin:
        mpv_process.stdin.close()
    mpv_process.wait()

   return bytes #Return bytes object
```

Would add further versatility to the stream function, and simplify users ability to interact with the stream without needing to write their own solutions.

**Comment by flavioschneider** [comment]
Hi @Agent-R-QT, that's a good idea! This has been added in `v0.2.13`
