### ISSUE TITLE
Module 'elevenlabs' has no attribute 'generate'

### ISSUE THREAD

**Issue by Abxent** [elevenlabs/elevenlabs-python#240]
Here's my code-

import elevenlabs
audio = elevenlabs.generate(
    text = "Hello",
    voice = "Bella"
)
elevenlabs.play(audio)

The error-
 audio = elevenlabs.generate(
            ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'elevenlabs' has no attribute 'generate'

and no, it is not due to circular import

**Comment by ruhullahshaikh** [comment]
just type
 
`pip install -U elevenlabs`

update to latest version and restart the envronment.

**Comment by Abxent** [comment]
tried it, still nothing

**Comment by dsinghvi** [comment]
Please see the readme for the latest migration! You want to do `client.generate()` after instantiating the client.

**Comment by bsullins** [comment]
Can we re-open this to update the documentation? It's still showing the old way.

**Comment by elenadadshian** [comment]
PS C:\Users\ASUS> & C:/Users/ASUS/AppData/Local/Programs/Python/Python311/python.exe "c:/Users/ASUS/Desktop/New folder (3)/jdid.py"
Traceback (most recent call last):
  File "c:\Users\ASUS\Desktop\New folder (3)\jdid.py", line 2, in <module>
    from elevenlabs import generate, stream
ImportError: cannot import name 'generate' from 'elevenlabs' (C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\elevenlabs\__init__.py) please help
