### ISSUE TITLE
Change audio Settings

### ISSUE THREAD

**Issue by Soykertje** [elevenlabs/elevenlabs-python#25]
This is more a feature request than a bug, the function `generate` should be able to receive the parameters `similarity_boost` and `stability` to set them, when I generate multiple short audio files and put them together it's very obvious the inconsistency mainly in the accent and the speed.

I tried changing it by myself by editing the function `generate` but when I make the request to change those parameters, it raises an error:
`
Traceback (most recent call last):
  File "elevenlabs/api/base.py", line 44, in request
    error = HTTPError(response)
  File "elevenlabs/api/error.py", line 14, in __init__
    self.message = detail["message"]
TypeError: string indices must be integers
`

and the response object is:
`
{'_content': b'{"detail":"Method Not Allowed"}', '_content_consumed': True, '_next': None, 'status_code': 405, 'headers': {'date': 'Mon, 15 May 2023 04:46:29 GMT', 'server': 'uvicorn', 'allow': 'POST', 'content-length': '31', 'content-type': 'application/json', 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'POST, OPTIONS, DELETE, GET', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}, 'raw': <urllib3.response.HTTPResponse object at 0x0000023FD28EDAF0>, 'url': 'https://api.elevenlabs.io:443/v1/voices/E9mF8hLERgWtuXDxqdi3/settings/edit', 'encoding': 'utf-8', 'history': [<Response [307]>, <Response [301]>], 'reason': 'Method Not Allowed', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=79914), 'request': <PreparedRequest [GET]>, 'connection': <requests.adapters.HTTPAdapter object at 0x0000023FD2896820>}
`

**Comment by flavioschneider** [comment]
This is already possible by changing the settings for the provided voice object, there's an example in the [API doc](https://github.com/elevenlabs/elevenlabs-python/blob/main/API.md#voices-1): 

```py
my_voice = voices[0]
my_voice.settings.stability = 0.1
my_voice.settings.similarity_boost = 0.75

text = f""" Hi! My name is {my_voice.name}, nice to meet you! """
audio = generate(text, voice=my_voice)
```

**Comment by Soykertje** [comment]
Ohhh thank you @flavioschneider I ended up doing a requests with the API key but that solution is better.
