### ISSUE TITLE
How do I specify pronunciation_dictionary_locators?

### ISSUE THREAD

**Issue by arkpatrick** [elevenlabs/elevenlabs-python#258]
My code looks similar to the code below. Can someone explain how I can specify the `pronunciation_dictionary_locators`?

```
import elevenlabs

voice = elevenlabs.Voice(
    voice_id=...,
    settings=elevenlabs.VoiceSettings(
    ...
    )
)
raw_audio = elevenlabs.generate(
    voice=voice
    ...
)
```

**Comment by lharries** [comment]
Please see example code here: https://github.com/elevenlabs/elevenlabs-examples/pull/12/files

**Comment by marco79cgn** [comment]
Hi @lharries , 

I tried this several times but as a result, the resulting voice file doesn't include the replaced word at all. The replaced/corrected word is left out completely when applying the dictionary. I even tried it with your linked tomato example, same result. Is this a bug or am I doing something wrong? 

```
curl \                                                                                                                                                                          ✔  11:32:41  
  --request POST \
  --url 'https://api.elevenlabs.io/v1/text-to-speech/GBv7mTt0atIp3Br8iCZE?output_format=mp3_44100_64' \
  --header 'Content-Type: application/json' \
  --header 'xi-api-key: b8********cf' \
  --data '{
     "voice_settings": {
     "stability": 0.5,
     "similarity_boost": 0.5,
     "style": 0.25,
     "use_speaker_boost": true
  },
  "text": "I like Tomato soup",
  "model_id": "eleven_multilingual_v2",
  "pronunciation_dictionary_locators": [
    {
      "pronunciation_dictionary_id": "FYJY4zwOVFnl472bBCbm",
      "version_id": "Z4BOJZzn46kxwrroqTjy"
    }
  ]
}' -o example-tomato-dict.mp3
```

**Comment by lharries** [comment]
hi @marco79cgn, if you use the code here - copy over .env.example to .env, `pip install -r requirements.txt` and then run `python main.py` it should work for you

I'll look into why the curl doesn't work

**Comment by marco79cgn** [comment]
Thanks for your quick reply @lharries 
I changed the file ending of my dictionary from xml to pls but unfortunately that doesn't change anything. It strips out the word tomato completely. 

If I - like in your example - leave out the _voice_settings_ and the _model_id_ in the data payload and just use text and dictionary, I don't get a result at all but I receive this error message: 
```
{"detail":[{"loc":["body",9],"msg":"Extra data: line 2 column 9 (char 9)","type":"value_error.jsondecode","ctx":{"msg":"Extra data","doc":"\n  \"text\": \"I like tomato soup\",\n  \"pronunciation_dictionary_locators\": [\n    {\n      \"pronunciation_dictionary_id\": \"grx7YzcqiKUmEqHPkc60\",\n      \"version_id\": \"I8OCfggPXsz9ER1q3dpR\"\n    }\n  ]\n}","pos":9,"lineno":2,"colno":9}}]}
```
Maybe there's an error in my dictionary? I copied it from your [source](https://raw.githubusercontent.com/elevenlabs/elevenlabs-examples/00ccad4d173bc3dfe26d5ec93ccf68d1bd1ef8dc/examples/pronunciation-dictionaries/python/dictionary.pls).

**Comment by lharries** [comment]
Can you try switching to the turbo v2 model and see if it works with that?

I think it silently skips the word if the model doesn't supported phoneme pronunciation rules

We will also have a tutorial soon for alias rules which should be more widely supported by models

**Comment by lharries** [comment]
Also, can if you run the python code in the example directly does that work for you?

**Comment by marco79cgn** [comment]
> Can you try switching to the turbo v2 model and see if it works with that?
> 
> I think it silently skips the word if the model doesn't supported phoneme pronunciation rules

That's it! The turbo v2 model is the only one that works (in english-only of course, since this model doesn't support german). Both the multilingual v1 and v2 models don't work and instead skip the words.

I'll try the python code next.

**Comment by lharries** [comment]
I've added more guidance to the docs here:
> Alias tags are supported by all models. Phoneme tags only work with the models eleven_turbo_v2 and eleven_monolingual_v1. If you use phoneme tags with other models, they will silently skip the word.

And we have instructions of how to use Alias tags coming soon

https://elevenlabs.io/docs/api-reference/how-to-use-pronunciation-dictionaries
