### ISSUE TITLE
Error with dubbing sdk - get_dubbing_project_metadata and get_dubbed_file aren't working

### ISSUE THREAD

**Issue by lharries** [elevenlabs/elevenlabs-python#259]
`client.dubbing.get_dubbing_project_metadata(dubbing_id=id)` errors with the following:
![Screenshot client py — elevenlabs-playground (Cursor) 2024-04-16 at 10 10@2x](https://github.com/elevenlabs/elevenlabs-python/assets/22766134/7b688dae-dde0-43a0-891b-10fbef224174)

and `client.dubbing.get_dubbed_file` returns None when it should return the file information

Here's an example including the version with requests that works as expected and commented out versions of the dubbing file

https://github.com/elevenlabs/elevenlabs-examples/pull/6/files#diff-07934421fcacdb2418d4e464c326244d4da106ccf4da7ebde5bfb361279023b6

**Comment by dsinghvi** [comment]
@lharries the latest version of the SDK disables hard failures from pydantic, please reopen if you see this behavior again!

**Comment by lharries** [comment]
Hi @dsinghvi, this issue with "client.dubbing.get_dubbed_file returns None when it should return the file information" is still happening, this is related to the `application/octet-stream` streaming response that we spoke about

**Comment by dsinghvi** [comment]
The get_dubbed_file now returns [bytes](https://github.com/elevenlabs/elevenlabs-python/blob/0710d299269ecfda8b51da83aa5f2a245e0c0919/src/elevenlabs/dubbing/client.py#L280-L283)
