### ISSUE TITLE
High latency using official API

### ISSUE THREAD

**Issue by cyrilS-dev** [elevenlabs/elevenlabs-python#268]
I'm using the official API with Eleven Multilingual v1 model, and i have a pretty high latency, around 1600ms to get the text-to-speech content played.

Here is my code :

```python
import asyncio
import time
from elevenlabs.client import AsyncElevenLabs
from elevenlabs import play, Voice, VoiceSettings
from openai import AsyncOpenAI

global start

clientEL = AsyncElevenLabs(
    api_key=XX
)
openai_client = AsyncOpenAI(
   api_key=XX
)

async def main() -> None:
    while True:
        async def text_stream():
            global start
            start1 = time.time()
            print ('Generating content')
            openai_stream = await openai_client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": "Dis moi une de 12 mots d'une conversation commerciale aléatoire."}],
                stream=True,
            )
            generated_text = ""
            async for chunk in openai_stream:
                content = chunk.choices[0].delta.content
                if content is not None:
                    generated_text += content
            end1 = time.time()
            print (generated_text)
            print(f"Content :  {end1 - start1}")
            print ('Play voice')
            start = time.time()
            return generated_text

        audio_stream = await clientEL.generate(
            text=await text_stream(),
            voice=Voice(
                voice_id='glDtoWIoIgk38YbycCwG',
                settings=VoiceSettings(stability=0.71, similarity_boost=0.5, style=0.0, use_speaker_boost=True)
            ),
            model="eleven_multilingual_v1",
            stream=True
        )
        out = b''
        async for value in audio_stream:
            out += value
        end = time.time()
        play(out)
        print(f"Text to speech :  {end - start}")
    

asyncio.run(main())
```

Some output : 

> Generating content
> "Quel est votre budget pour ce projet? Pouvez-vous me donner des indications précises?"
> Content :  0.8194494247436523
> Play voice
> Text to speech :  1.7442007064819336
> Generating content
> "Pourriez-vous me donner plus d'informations sur les options de financement disponibles?"
> Content :  0.7206406593322754
> Play voice
> Text to speech :  1.5337841510772705
> Generating content
> "Bonjour, je suis intéressé par vos produits, pourriez-vous me donner plus d'informations?"
> Content :  0.8179852962493896
> Play voice
> Text to speech :  1.6968724727630615
> Generating content
> "Bonjour, je suis intéressé par votre produit, pourriez-vous me donner plus d'informations s'il vous plaît?"
> Content :  1.080442190170288
> Play voice
> Text to speech :  1.6775517463684082

Do you have any recommendations for improving my code? Thanks

**Comment by lharries** [comment]
Hi, @cyrilS-dev, that latency is including both the LLM and ElevenLabs

Here's our guide on improving latency: https://elevenlabs.io/docs/api-reference/reducing-latency

Currently the turbo model only supports English but we have more in the works there

**Comment by cyrilS-dev** [comment]
Hi @lharries , thanks for your reply. That latency includes only TTS part; LLM part is separated ("Content" counter into the output).

**Comment by lharries** [comment]
You might find this script useful too which we often use to measure latency: https://gist.github.com/am-holt/1cfd15f71ae1182404cb20cafcd184a4

We have a websocket and enhanced latency guide coming soon too

**Comment by lharries** [comment]
Our lowest latency only support english for the moment - but this is something we are actively working on

**Comment by teis-e** [comment]
> You might find this script useful too which we often use to measure latency: https://gist.github.com/am-holt/1cfd15f71ae1182404cb20cafcd184a4
> 
> We have a websocket and enhanced latency guide coming soon too

This is a very usefull script! But i don't understand the openAI generation part. Where does the streaming of reponse chunks of openai happen e.g:
```
async def chat_completion():
    """Retrieve text from OpenAI and pass it to the text-to-speech function."""
  
  
    async def text_iterator():
        words = 0
        to_send = ""
        response = await openai_client.chat.completions.create(
            model="gpt-4o",
            messages=gpt_messages,
            max_tokens=128,
            stop=['\n\n', '---'],
            stream=True
        )
        async for chunk in response:
            content = chunk.choices[0].delta.content
            if content is not None:
                print(content)
                to_send += content  + ' '
                words += 1
                if words >= 10:
                    yield to_send
                    words = 0
                    to_send = ""
    await text_to_speech_input_streaming("EuQDS5FR7dD1UoZkGdbZ", text_iterator())
```
This does work and stream but the first byte is recivied after the whole response is done ( i have tested with high token count to account for the timing)
