### ISSUE TITLE
mpv install instructions

### ISSUE THREAD

**Issue by fib1123** [elevenlabs/elevenlabs-python#27]
Hey! 
When trying 'stream' function there is the following error: 
`ValueError: mpv not found, necessary to stream audio.`

Please add instruction in README.md how to resolve it. I had problems installing it to my python env. I tried both pympv and mpv without success

Thanks and congrats on having great T2S models!

**Comment by flavioschneider** [comment]
Hi, depending on your system you can find instructions here https://mpv.io/installation/. On macos it's just `brew install mpv`.

**Comment by fib1123** [comment]
Thank you! Brew install worked smoothly

**Comment by RicardoEscobar** [comment]
I installed it on windows 10, but I get the same error

**Comment by SHARKgamestudio** [comment]
Same, installed MPV in windows path but i still have the error..
I think the python binding is just not made to work properly on windows :(
