### ISSUE TITLE
ipython-dependency interferes with server-side setup

### ISSUE THREAD

**Issue by th3hamm0r** [elevenlabs/elevenlabs-python#294]
We currently have issues with the required dependency of [ipython](https://github.com/elevenlabs/elevenlabs-python/blob/eca8ec7670bbd6dc1f4db07e3eb964c14d265466/pyproject.toml#L14) with our server environment (django). Is it possible to make it an optional dependency?

The only usage of ipython seems to be here: https://github.com/elevenlabs/elevenlabs-python/blob/eca8ec7670bbd6dc1f4db07e3eb964c14d265466/src/elevenlabs/play.py#L21
Since server environments usually don't have speakers and won't play anything, this seems to be an unnecessary dependency there.

**Comment by dsinghvi** [comment]
@th3hamm0r definitely -- we'll follow up when this change is fixed!
