### ISSUE TITLE
`clone(...)` returns `str` not `Voice`

### ISSUE THREAD

**Issue by regisin** [elevenlabs/elevenlabs-python#30]
I've never done a PR before, I don't even know if it's allowed. Here's the code I had:

```python
    voice = clone(
        name=name,
        files=[str(sample_path)]
    )
    voice.settings.similarity_boost = order.similarity
    voice.settings.stability = order.stability
```
But that raises an exception `AttributeError: 'str' object has no attribute 'settings'`

So the solution I found was:

```python
    voice_id = clone(
        name=name,
        files=[str(sample_path)]
    )
    voice = Voice.from_id(voice_id=voice_id)
    voice.settings.similarity_boost = order.similarity
    voice.settings.stability = order.stability
```

While I got it working for myself, I looked into the implementation, and the code is misleading:

From [Voice.py](https://github.com/elevenlabs/elevenlabs-python/blob/main/elevenlabs/api/voice.py):
```python
class Voice(API):
    ...

    @classmethod
    def from_clone(cls, voice_clone: VoiceClone) -> Voice:
        url = f"{api_base_url_v1}/voices/add"
        data = voice_clone.dict()
        data["lables"] = str(data.pop("labels"))
        del data["files"]
        files = data.pop("_files_tuple")
        try:
            voice_id = API.post(url, data=data, files=files).json()["voice_id"]
        except APIError as e:
            if e.http_error.status == "can_not_use_instant_voice_cloning":
                raise UnauthorizedVoiceCloningError(e.http_error)
            raise
        return voice_id

    ...
```

We can see that `from_clone(...) -> Voice` should return a `Voice` object, but instead it returns `voice_id` which is the voice id returned by the http request, a string. Perhaps `return Voice.from_id(voice_id)` would avoid the problem?

**Comment by flavioschneider** [comment]
Hi! You are right, `clone` should return a `Voice` object. This has been fixed in `v0.2.16`
