### ISSUE TITLE
When is dubbing from csv_file supported

### ISSUE THREAD

**Issue by raimmm** [elevenlabs/elevenlabs-python#312]
Hi! Thanks for your great work. Could you please tell me when to enable csv_file and other parameters in dubbing, such as specifying the subtitles you input.

**Comment by dsinghvi** [comment]
Appreciate the kind words -- the `csv` option should now be supported. See [here](https://github.com/elevenlabs/elevenlabs-python/blob/2388145bc7664f4f5838b8d1963788821dbb17db/src/elevenlabs/dubbing/client.py#L36)
