### ISSUE TITLE
Typo in function name: convert_with_timstamps

### ISSUE THREAD

**Issue by keaganaut** [elevenlabs/elevenlabs-python#322]
There appears to be a typo in the function name `convert_with_timstamps`

https://github.com/elevenlabs/elevenlabs-python/blob/7af17bce7abcfa5e761ab02813ed592ab581da1c/src/elevenlabs/text_to_speech/client.py#L191

It's not breaking anything, but it might confuse some folks using the SDK 😅

**Comment by dsinghvi** [comment]
@keaganaut great call -- we will fix this (and make sure it stays backwards compatible)

**Comment by dsinghvi** [comment]
@keaganaut we shipped the change as a break b/c it affected class names as well. This is available on the latest `1.7.x`
