### ISSUE TITLE
Use pydantic v2?

### ISSUE THREAD

**Issue by mbforbes** [elevenlabs/elevenlabs-python#323]
Hi all, have you considered talking with Fern to use pydantic v2 for this library?

Pydantic v2 has been out for over a year, is already on v2.8, and continues to get improvements. It's awkward to mix pydantic v1 and v2 calls in the same codebase.

Only relevant issue I found:
https://github.com/fern-api/python-sdk/issues/4

Thanks for your consideration!

**Comment by dsinghvi** [comment]
@mbforbes we are recently going to be releasing a change in the next 2 weeks where the SDK will use Pydantic V2 for those who are pinned to V2 versions and Pydantic V1 for those who are on V1. Thanks for submitting this feedback!

**Comment by dsinghvi** [comment]
@mbforbes this is released in `v1.6.0rc0`, please let us know if you have any issues!
