### ISSUE TITLE
Update History to support pagination

### ISSUE THREAD

**Issue by lugia19** [elevenlabs/elevenlabs-python#35]
The /history/ endpoint was changed to support pagination, and now only returns the latest 100 history items by default, so the current code doesn't actually return all the items. 

You could either change the code to silently call the endpoint multiple times to get all the items, or add more explicit support for the pagination.

Here's how I personally did it https://github.com/lugia19/elevenlabslib/blob/master/elevenlabslib/ElevenLabsUser.py#L215

**Comment by flavioschneider** [comment]
Hi @lugia19, thanks for the issue! I ended up adding both: either `History.from_api(page_size, start_after_history_item_id)` to do it manually, or with an iterator that automatically paginates as you yield more items:

```py
for item in History.from_api(): # This will automatically paginate as more items are fetched
  print(item.history_item_id) 
```
