### ISSUE TITLE
We are sorry, something went wrong. You are not charged for this request.

### ISSUE THREAD

**Issue by Stgrgtt** [elevenlabs/elevenlabs-python#351]
I'm trying to create a python app to livestream my altered voice to discord. I believe I've managed to setup everything correctly but when I start my stream, I'm getting the following error:
Error during streaming: status_code: 500, body: {'detail': {'status': 'something_went_wrong', 'message': 'We are sorry, something went wrong. You are not charged for this request.'}}
I'm unable to debug this as it seems to be some issue on 11Labs side.
Any Ideas of what could be wrong?

Thanks

**Comment by dsinghvi** [comment]
@Stgrgtt closing this issue, since reaching out to support will be a better way to get an answer
