### ISSUE TITLE
Generating chunk audios

### ISSUE THREAD

**Issue by ibiscp** [elevenlabs/elevenlabs-python#37]
I'm currently using the Elevenlabs API for TTS, converting outputs from GPT-4 into audio. To improve performance, I aim to generate the audio output in chunks instead of waiting for the full output before beginning TTS.

My approach was to break the output from the language model at punctuation points. However, I've encountered an issue with this strategy when using the Elevenlabs API. Specifically, when I piece together the audio chunks generated, there are noticeable mismatches and inconsistencies. Even the tone of the speech appears to change between chunks.

Also, the streaming is only for the output, would it be possible to have input streaming as well?

Has anyone faced similar situation?

**Comment by maxilevi** [comment]
Hey there,

Just wanted to let you know we are working on adding streaming input support to the TTS API. This should fix the issue

**Comment by hanifsma** [comment]
yes.  I am also looking for the same solution. I want to process the audio chunks before completion of stream()

**Comment by ibiscp** [comment]
Here is a demonstration of the problem I'm facing, if I generate the full sentence at once it is perfect, but if I decide to put the pieces together the result is not that good. Also, at the end of each sentence, there is a weird sound effect.

https://www.loom.com/share/0ef9271d544d4b7da25f9e0288a4d1e6

**Comment by ibiscp** [comment]
Flavio, thank you for the answer, the voice is not cloned, I'm using "Domi".

I also tried to play around with `similarity_boost` and `stability`, but could not get the result I was expecting.

I will implement the streaming as well, but I know that without input stream it will not yet solve my issue, do you have input streaming in your roadmap?

**Comment by flavioschneider** [comment]
Unfortunately without context it's hard to maintain stability to the previously generated chunks - the model doesn't have any way to know the tone used by the previous chunk. We are aware that this is an important feature for many use-cases, such as low latency streaming from/to chatbots. 

> do you have input streaming in your roadmap?

Yes, this is in the works :)

**Comment by grp06** [comment]
Any update on this? Super important for working with LLMs

**Comment by flavioschneider** [comment]
Yes! Input streaming has been added in `v0.2.22`.

```py
from elevenlabs import generate, stream

def text_stream():
    yield "Hi there, I'm Eleven "
    yield "I'm a text to speech API "

audio_stream = generate(
    text=text_stream(),
    voice="Nicole",
    model="eleven_monolingual_v1",
    stream=True
)

stream(audio_stream)
```
