### ISSUE TITLE
Feature request: mechanism for hinting how text should be read 

### ISSUE THREAD

**Issue by dhowe** [elevenlabs/elevenlabs-python#38]
In the docs, you talk about using something like _"That's not funny", he said seriously._ which works nicely if you can then post-process the audio to remove the 'he said seriously'. But it doesn't work at all when using live text-to-speech and streaming. 

We really need some way to give the model hints at how to say something _without_ those hints ending up in the spoken audio.

**Comment by flavioschneider** [comment]
Will close this – feature requests can be requested here https://feedback.elevenlabs.io/suggestions
