### ISSUE TITLE
AttributeError: module 'elevenlabs' has no attribute 'generate'

### ISSUE THREAD

**Issue by ZombieSmile0** [elevenlabs/elevenlabs-python#381]
### Description

I just keep getting this error and i dont know why. I am new to this

### Code example

import elevenlabs

audio = elevenlabs.generate(
    text = "Hi, I'm from the future!",
    voive = "Adam"
)

elevenlabs.play(audio)

**Comment by ZombieSmile0** [comment]
i think i accidentally labeled it as a bug i apologize

**Comment by dsinghvi** [comment]
@ZombieSmile0 you need to instantiate the client: 

```
from elevenlabs import ElevenLabs

client = ElevenLabs(
  api_key="YOUR_API_KEY", # Defaults to ELEVEN_API_KEY
)

audio = client.generate(
  text="Hello! 你好! Hola! नमस्ते! Bonjour! こんにちは! مرحبا! 안녕하세요! Ciao! Cześć! Привіт! வணக்கம்!",
  voice="Brian",
  model="eleven_multilingual_v2"
)
```
