### ISSUE TITLE
Define / Add a pronunciation Dictionary when creating a Dub via the API 

### ISSUE THREAD

**Issue by gu-ma** [elevenlabs/elevenlabs-python#394]
Hello,

I posted this in the `elevenlabs-docs` repo but maybe it's better to have it here:

https://github.com/elevenlabs/elevenlabs-docs/issues/448

Thanks.

**Comment by fern-support** [comment]
@gu-ma this is a better issue for the docs repo, thanks!

**Comment by gu-ma** [comment]
Oh... Forgot, about this issue. More than a month wait for this though... 🙀 and, crickets on the elevenlabs-docs repo as well.
