### ISSUE TITLE
TextToSpeechClient.stream_with_timestamps does not return or yield response

### ISSUE THREAD

**Issue by dglinyanov** [elevenlabs/elevenlabs-python#396]
### Description

I was trying to use Python SDK to have a stream with timestamps. 
But turns out that `TextToSpeechClient.stream_with_timestamps` does not yield chunks of HTTP response and returns `None` instead of `typing.Iterator[bytes]`.

Here is the place where I suppose something should be yielded or returned:
https://github.com/elevenlabs/elevenlabs-python/blob/main/src/elevenlabs/text_to_speech/client.py#L637

For example, neighbor method `convert_as_stream` yields chunks of specified size:
https://github.com/elevenlabs/elevenlabs-python/blob/main/src/elevenlabs/text_to_speech/client.py#L488

Unless I am not able to see some meta magic, same piece of code as in `convert_as_stream` should do the job. But I do not know, how can I send a PR to autogenerated code or do something further.

### Code example

```
client = ElevenLabs(api_key=settings.ELEVENLABS_API_KEY)

audio_stream = client.text_to_speech.stream_with_timestamps(
    text=text,
    voice_id=settings.ELEVENLABS_VOICE_ID,
    model_id='eleven_multilingual_v2',
)

# audio_stream is None, but I expected typing.Iterator[bytes] or something like that.
```

### Additional context

If someone has the same problem while this is being fixed, you can subclass original `TextToSpeechClient`, override `stream_with_timestamps` with suggested fix and then use it directly, e.g. like:

```
client = ElevenLabs(api_key=settings.ELEVENLABS_API_KEY)
tts = TextToSpeechClient(client_wrapper=client.text_to_speech._client_wrapper)

audio_stream = tts.stream_with_timestamps(
    text=text,
    voice_id=settings.ELEVENLABS_VOICE_ID,
    model_id='eleven_multilingual_v2',
)
```

**Comment by louisjoecodes** [comment]
Thank you very much for flagging this @dglinyanov & for fixing @rootux - I am updating our schema upstream and will re-generate this piece & push a new version.
