### ISSUE TITLE
VoiceChanger example would be welcome - SpeechToSpeechClient.convert_as_stream() - should require "audio" parameter?

### ISSUE THREAD

**Issue by gwpl** [elevenlabs/elevenlabs-python#397]
### Description

VoiceChanger  in playground:
https://elevenlabs.io/app/speech-synthesis/speech-to-speech
does not require any "audio" file. Just voice and parameters.
(btw. it would be very helpful is playground would generate working code snippets with parameters one set in playground...)

However in "speech-to-speech" API reference I see 
https://elevenlabs.io/docs/api-reference/speech-to-speech
that "audio" is marked as "required" for normal endpoint,
but is not in "streaming" endpoint.

However when I try to run as stream I get error to provide audio parameter:

```
elevenlabs_streaming_voice_to_voice.py Traceback (most recent call last):
  File "/.../elevenlabs_streaming_voice_to_voice.sh", line 15, in <module>
    client.speech_to_speech.convert_as_stream(
TypeError: SpeechToSpeechClient.convert_as_stream() missing 1 required keyword-only argument: 'audio'
```

Also there is parameter annotated as "voice_settings" , as "json parameters", to be frank it's pretty hard how to go from parameters in playground ( https://elevenlabs.io/app/speech-synthesis/speech-to-speech ) to json, there should be button "copy as json" that would copy to clipboard, or sth like that. (or whole code snippet generation)

### Code example

```python
#!/usr/bin/env python3

from elevenlabs import ElevenLabs

client = ElevenLabs(
#    api_key="YOUR_API_KEY", #commented to use environment variable
)
## Brian
voice_id='nPczCjzI2devNBz1zQrb'

# as making minimal working example, commenting parameters that are optional to see if it works
client.speech_to_speech.convert_as_stream(
    voice_id=voice_id,
    enable_logging="0",
    #output_format="mp3_22050_32", #default: mp3_44100_128 #should work with default value
    #remove_background_noise=true, #default: false #should work with default value
)
```

**Comment by dsinghvi** [comment]
@gwpl you should be able to use this playground https://elevenlabs.docs.buildwithfern.com/api-reference/speech-to-speech/convert?playground=%2Fapi-reference%2Fspeech-to-speech%2Fconvert to get a code snippet. 

@louisjoecodes this is another reason why the Fern playground may help support users

**Comment by louisjoecodes** [comment]
Nice!
