### ISSUE TITLE
Does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by dataplayer12** [elevenlabs/elevenlabs-python#4]
I have been trying to make the api work on my ubuntu 18.04 system, but after >20 minutes of upgrading `pip`, `python` and `setuptools`, I am no closer to making anything work. 
![E4BDAEB0-8352-4A59-A1EC-ED086746CF44](https://user-images.githubusercontent.com/11517109/233822193-9edd4d3e-8763-47d9-b356-adec5e7de193.jpeg)

**Comment by PiotrDabkowski** [comment]
Looks like broken `urllib3` installation. Try `import urllib3` and see if this works.
