### ISSUE TITLE
when streaming --Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%.

### ISSUE THREAD

**Issue by MohammedJesim** [elevenlabs/elevenlabs-python#40]
**audio = generate(
  text="This is a... streaming voice!!",
  stream=True
)
stream(audio)**

when try to run this below err appears:

**Traceback (most recent call last):
  File "D:\ElevenLabs\test.py", line 7, in <module>
    import mpv
  File "C:\Users\Admin\.virtualenvs\ElevenLabs-zG-NPETf\lib\site-packages\mpv.py", line 
38, in <module>
    raise OSError('Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%. One way to 
deal with this is to ship '
OSError: Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%. One way to deal with 
this is to ship the dll with your script and put the directory your script is in into %PATH% before "import mpv": os.environ["PATH"] = os.path.dirname(__file__) + os.pathsep + 
os.environ["PATH"] If mpv-1.dll is located elsewhere, you can add that path to os.environ["PATH"].**

but i already installed mpv and successfully path assinged

C:\Users\Admin>mpv
mpv 0.35.0-407-g959ef843 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun May 28 12:30:13 2023
libplacebo version: v5.264.0-264-g20d63f7

**Comment by flavioschneider** [comment]
Have you tried to

> <b> ship the dll with your script and put the directory your script is in into %PATH% before "import mpv"</b>

**Comment by VitalikPro13** [comment]
Hey there! I had a similar issue with audio streaming. First, you need to download MPV release from here https://sourceforge.net/projects/mpv-player-windows/files/release/ (I downloaded mpv-0.35.1-x86_64.7z). Unpack and place in your desired folder. After that, head over to your Environment Variables and place to PATH your folder with all MPV files. Restart IDE and run the script. The audio streaming should work now!

My code:
```
import os
from elevenlabs import generate, set_api_key, stream

my_api_key = os.getenv("xi-api-key")
set_api_key(my_api_key)

audio = generate(
    text="Hi! How are you doing? This is a test for the voice generation inside Python script",
    voice="MY VOICE ID", #replace with your actual ID or name etc.
    model="eleven_monolingual_v1",
    stream=True
)

stream(audio)
```

**Comment by TKassis** [comment]
MPV as a dependency for streaming seems to be causing a lot of issues. Why not use something that doesn't require external installation for streaming audio playback? I've been using Pygame and haven't had any issue on Linux or Windows.
