### ISSUE TITLE
ModuleNotFoundError: No module named 'elevenlabs.client'

### ISSUE THREAD

**Issue by jackyurkanin** [elevenlabs/elevenlabs-python#408]
### Description

1. from elevenlabs.client import ElevenLabs

pip show elevenlabs: Version: 0.2.26
module for elevenlabs is available and accessible. Only trouble comes from elevenlabs.client

**Comment by jackyurkanin** [comment]
Fixed it with: pip install git+https://github.com/elevenlabs/elevenlabs-python@v3

**Comment by dsinghvi** [comment]
@jackyurkanin you need to be on version 0.3.x or above (the latest is on 1.x)
