### ISSUE TITLE
get_signed_url is wrongly referenced from eleven labs client for conv-ai  

### ISSUE THREAD

**Issue by Niteshiya** [elevenlabs/elevenlabs-python#413]
### Description

Error
```   
 ws_url = self._get_signed_url() if self.requires_auth else self._get_wss_url()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/homeos/nitesh/act_reporter/venv/lib/python3.12/site-packages/elevenlabs/conversational_ai/conversation.py", line 233, in _get_signed_url
    response = self.client.get_signed_url(agent_id=self.agent_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ElevenLabs' object has no attribute 'get_signed_url'
```

### Code example

File loc : venv/lib/python3.12/site-packages/elevenlabs/conversational_ai/conversation.py
```
def _get_signed_url(self):
        response = self.client.get_signed_url(agent_id=self.agent_id)
        return response.signed_url
```

### Additional context

I resolved the issue with a small change in the code. Initially, the method was written as follows:
File : venv/lib/python3.12/site-packages/elevenlabs/conversational_ai/conversation.py
```
def _get_signed_url(self):
        
        response = self.client.get_signed_url(agent_id=self.agent_id)
        return response.signed_url
```
However, this was incorrectly referencing the Eleven Labs client, which doesn’t have a get_signed_url method.
the corrected version 
```
def _get_signed_url(self):  
    response = self.client.conversational_ai.get_signed_url(agent_id=self.agent_id)  
    return response.signed_url
```
By properly directing the call to conversational_ai, the issue is resolved, and the method works as expected.

**Comment by hikmet-demir** [comment]
Thank you Niteshiya for the bug report and solution recommendation! @OsKrg deploying the fix now

**Comment by fern-support** [comment]
@Niteshiya this should be fixed now!
