### ISSUE TITLE
Voice ID Override Not Applied in Conversational SDK

### ISSUE THREAD

**Issue by jcassady** [elevenlabs/elevenlabs-python#424]
## Description
The `voice_id` parameter is configurable in the ElevenLabs Python SDK for the `ConversationConfig` class. However, after tracing the SDK's conversational code paths, it appears that the `voice_id` provided in the configuration is not integrated into the voice configuration for the agent during a conversational session. 

This results in the default server-side voice configuration being used, even when a `voice_id` is explicitly passed in the client code.

## Steps to Reproduce
1. Use the `Conversation` class with a `ConversationConfig` that specifies an `extra_body` containing a `voice_id`.
2. Start a conversational session.
3. Observe that the voice used in the session is the default server-side voice configured in the ElevenLabs web UI for the given agent, rather than the one specified in the `voice_id`.

## Code Example
```python
from elevenlabs.conversational_ai.conversation import Conversation, ConversationConfig
from elevenlabs.base_client import ElevenLabsClient
```

### Replace with your actual keys and IDs
```python
voice_id = "EXAVITQu4vr4xnSDxMaL"
agent_id = "AAXnoxx5oa6YeDkMnUgx"
api_key = "your_api_key_here"

client = ElevenLabsClient(api_key=api_key)
conversation_config = ConversationConfig(extra_body={"voice_id": voice_id})
conversation = Conversation(client=client, agent_id=agent_id, config=conversation_config)
```

### Start the conversation
```python
conversation.start_session()
```

## Additional Context
- **Related SDK Files**:
  - `conversation.py`: `_run` method in `Conversation` sends configuration to the API but does not reference `voice_id`.
    ```python
    def _run(self, ws_url: str):
        with connect(ws_url) as ws:
            ws.send(
                json.dumps(
                    {
                        "type": "conversation_initiation_client_data",
                        "custom_llm_extra_body": self.config.extra_body,
                        "conversation_config_override": self.config.conversation_config_override,
                    }
                )
            )
    ```
  - `voice.py`: `voice_id` is defined in the `Voice` class but not referenced in the conversational flow.
    ```python
    class Voice(UncheckedBaseModel):
        voice_id: str
    ```

- **Suggested Fix**:
  1. Ensure that `voice_id` is read and passed in the API payload during session initialization.
  2. Update the `_run` method in `conversation.py` to include `voice_id` explicitly.

- **Environment**:
  - SDK Version: 1.13.3
  - Python Version: 3.x
  - Platform: All

**Comment by louisjoecodes** [comment]
Hello @jcassady, thanks for the detailed report.

Could you try wrapping the `voice_id` paramater in `tts` as described below:
https://elevenlabs.io/docs/conversational-ai/customization/conversation-configuration
```
from elevenlabs.conversational_ai.conversation import Conversation, ConversationConfig

# dynamically change the first message based on the user's name
conversation_override = {
    "agent": {
        "prompt": {
            "prompt": f"The customer's bank account balance is {customer_balance}. They are based in {customer_location}."
        },
        "first_message": f"Hi {customer_name}, how can I help you today?",
        "language": <insert-override-language-here>,
    },
    "tts": {
        "voice_id": "iP95p4xoKVk53GoZ742B" # Override the voice
    }
}

config = ConversationConfig(
    conversation_config_override=conversation_override
)
conversation = Conversation(
    ...
    config=config,
    ...
)

```
{"type":"conversation_initiation_client_data","conversation_config_override":{"agent":{"first_message":"Хо, хо, хо! Весела Коледа, приятелю. Кажи ми, как се казваш?","language":"bg"},"tts":{}}}

**Comment by jcassady** [comment]
@louisjoecodes Thanks for sending the documentation link; I totally missed that section. Also, a big shoutout for sharing the Python version of the conversation config override, it's super useful!
