### ISSUE TITLE
is voices() needed to gain acess to the custom models

### ISSUE THREAD

**Issue by isayahc** [elevenlabs/elevenlabs-python#47]
I couldn't access my custom voices unless i called `voices()`. However, this isn't explicitly stated in the README.

**Comment by jonny7737** [comment]
Don't know if you already solved this but- Go to the ElevenLabs site and find the API playground. Uses the voices() call to get the output dig through the output for the voice you are looking for and copy the voice id.  Go back to your app and use the voice id as the value for the 'voice' parameter of the generate() call. 

Lot of assumptions in my statement - do not use it as step-by-step instruction but to inform your own intuition.

**Comment by flavioschneider** [comment]
This has been fixed in `v0.2.21` thanks!
