### ISSUE TITLE
ValueError: mpv not found, necessary to stream audio

### ISSUE THREAD

**Issue by nhtkid** [elevenlabs/elevenlabs-python#49]
Hi Fam,

I am trying to stream the audio using the sample code but getting MPV error.
The audio is getting generated fine with status code is 200, just not being played out automatically.

    response = requests.post(url, json=data, headers=headers, stream=True)
    print("The response status code is", response.status_code)

    # Generate audio using Eleven Labs
    audio_stream = generate(text=system_message, stream=True)

    # Stream the audio using Eleven Labs
    stream(audio_stream)

I am running the code in VSCode on Windows, but also hoping to run in Colab to share.
How do I get the MPV installed?

I looked into its repository so it is not straight forward.

**Comment by flavioschneider** [comment]
Have you tried installing the executable from https://mpv.io/installation/

**Comment by nhtkid** [comment]
It said unofficial so I didn't. I was looking for an official way but the documentation seems confusing.

**Comment by iKollor** [comment]
Any solution??

**Comment by iKollor** [comment]
Any solution??

**Comment by yunusdemir** [comment]
You could just install the unofficial executables, or build the application using the [source code](https://github.com/mpv-player/mpv/) yourself. The instructions to build the application are in the README of the source code.

Although, I would just install the 'unofficial' packages, especially as they're linked by the software builders themselves.

**Comment by flavioschneider** [comment]
If you're using a virtual environment you might have to set the path manually:

```
import os
os.environ['PATH'] += os.pathsep + '/path/to/mpv/'
```

**Comment by markgriswold** [comment]
I've added the path both to the original install and have tried moving the install inside my virtual environment. I'm on a Windows 10 machine. Should the link be to the parent folder of the application or one of the subfolders? Or should I use the dev version that contains the dll versions? I've tried both and both give the same error still. I'm clearly missing something. Thanks for your help!

**Comment by markgriswold** [comment]
Actually I just figured it out. It was cropping off the last path separator. My mistake! Thanks for the help!

**Comment by Ashish5869** [comment]
@yunusdemir how i can download mpv where is the option to download?

**Comment by nhtkid** [comment]
I got one more question.

If I need to deploy this as a web app via Streamlit, how can I have mpv in the requirements.txt as a Python library?

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by tschesnok** [comment]
Who closed this out??? For Ubuntu I'm supposed to go to "https://fruit.je/apt" and install something from some random dude?

**Comment by tschesnok** [comment]
Seriously.. spend a few hours building it from scratch.. or follow these instructions if you are on Ubuntu.. or you can't run a streaming demo without redesign:

Not sure what any of the following does.. but it sounds like a security nightmare. I'm not even sure it installs the right stuff:


Fruit's APT repository
I maintain a small apt repository with stuff I care about, and that may in some cases be useful for others as well.

What is available
Packages for [Fruitbak](https://fruit.je/fruitbak), [Kavoom](https://fruit.je/kavoom), libavl2, Firefox, the Linux kernel and more. Browse the [repository root](https://apt.fruit.je/) for a full list.

How to add it
1. Download the key
sudo curl --output-dir /etc/apt/trusted.gpg.d -O https://apt.fruit.je/fruit.gpg
2. Add a sources.list entry
Add the following to /etc/apt/sources.list.d/fruit.list:

deb http://apt.fruit.je/debian bullseye firefox
Replace http with https if you prefer (downloads are tamper-protected even over http though).

Replace debian with the name of the OS of your machine.

Replace bullseye with the OS codename of your machine.

Replace firefox with the list of components you're interested in.

To find the available operating systems and versions and the packages available for each, you can browse the [repository root](https://apt.fruit.je/).

3. Update the package list
sudo apt update
4. Install the package you're interested in
sudo apt install firefox

**Comment by RicardoEscobar** [comment]
The example:
```python
from elevenlabs import generate, stream

def text_stream():
    yield "Hi there, I'm Eleven "
    yield "I'm a text to speech API "

audio_stream = generate(
    text=text_stream(),
    voice="Nicole",
    model="eleven_monolingual_v1",
    stream=True
)

stream(audio_stream)
```
 doesn't work:

```
Traceback (most recent call last):
  File "C:\Users\Jorge\git\core-ai\controller\stream_completion.py", line 240, in <module>
    main()
  File "C:\Users\Jorge\git\core-ai\controller\stream_completion.py", line 229, in main
    audio_stream = generate(
                   ^^^^^^^^^
  File "C:\Users\Jorge\git\core-ai\venv\Lib\site-packages\elevenlabs\simple.py", line 115, in generate
    raise ValueError(f"Voice '{voice_str}' not found.")
ValueError: Voice 'Nicole' not found.
```

**Comment by RicardoEscobar** [comment]
I tried to fix it by replacing "Nicole" with "Bella" since Nicole is not found on the PRESET voices.
Then I got this error
```
File "C:\Users\Jorge\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
```
I fixed it by converting the generator object into a list:
```python
    def text_stream():
        yield "Hi there, I'm Eleven "
        yield "I'm a text to speech API "

    audio_stream = generate(
        text=list(text_stream()),
        voice="Bella",
        model="eleven_monolingual_v1",
        stream=True
    )

    stream(audio_stream)
```
I got this error, then I gave up:
```
Traceback (most recent call last):
  File "C:\Users\Jorge\git\core-ai\controller\stream_completion.py", line 240, in <module>
    main()
  File "C:\Users\Jorge\git\core-ai\controller\stream_completion.py", line 236, in main
    stream(audio_stream)
  File "C:\Users\Jorge\git\core-ai\venv\Lib\site-packages\elevenlabs\utils.py", line 55, in stream
    for chunk in audio_stream:
  File "C:\Users\Jorge\git\core-ai\venv\Lib\site-packages\elevenlabs\api\tts.py", line 38, in generate_stream
    response = API.post(url, json=data, stream=True, api_key=api_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\git\core-ai\venv\Lib\site-packages\elevenlabs\api\base.py", line 65, in post
    return API.request(url, method="post", *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\git\core-ai\venv\Lib\site-packages\elevenlabs\api\base.py", line 46, in request
    error = HTTPError(response)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge\git\core-ai\venv\Lib\site-packages\elevenlabs\api\error.py", line 14, in __init__
    self.message = detail["message"]
                   ~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by Holidayrabbit** [comment]
> 如果您使用虚拟环境，则可能必须手动设置路径：
> 
> import os
> os.environ['PATH'] += os.pathsep + '/path/to/mpv/'

thank you!
