### ISSUE TITLE
PydanticUserError during from import "from elevenlabs import set_api_key"

### ISSUE THREAD

**Issue by Psarpei** [elevenlabs/elevenlabs-python#51]
When doing the import "from elevenlabs import set_api_key" I get the following error:

---------------------------------------------------------------------------
PydanticUserError                         Traceback (most recent call last)
Cell In[24], line 1
----> 1 from elevenlabs import set_api_key

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/elevenlabs/__init__.py:1
----> 1 from .api import *  # noqa F403
      2 from .simple import *  # noqa F403
      3 from .utils import *  # noqa F403

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/elevenlabs/api/__init__.py:2
      1 from .base import *  # noqa F403
----> 2 from .history import *  # noqa F403
      3 from .model import *  # noqa F403
      4 from .tts import *  # noqa F403

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/elevenlabs/api/history.py:9
      6 from pydantic import root_validator
      8 from .base import API, Listable, api_base_url_v1
----> 9 from .voice import VoiceSettings
     12 class FeedbackItem(API):
     13     thumbs_up: bool

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/elevenlabs/api/voice.py:30
     26     size_bytes: Optional[int] = None
     27     hash: str = ""
---> 30 class VoiceClone(API):
     31     name: str = Field(..., min_length=1, max_length=100)
     32     description: str = ""

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/elevenlabs/api/voice.py:38, in VoiceClone()
     34 labels: Optional[Dict[str, str]]
     35 _files_tuple: Optional[List[Tuple]] = None
     37 @root_validator
---> 38 def computed_files_tuple(cls, values) -> List[str]:
     39     files_tuple = []
     40     for filepath in values["files"]:

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py:222, in root_validator(pre, skip_on_failure, allow_reuse, *__args)
    212 warn(
    213     'Pydantic V1 style `@root_validator` validators are deprecated.'
    214     ' You should migrate to Pydantic V2 style `@model_validator` validators,'
   (...)
    217     stacklevel=2,
    218 )
    220 if __args:
    221     # Ensure a nice error is raised if someone attempts to use the bare decorator
--> 222     return root_validator()(*__args)  # type: ignore
    224 if allow_reuse is True:  # pragma: no cover
    225     warn(_ALLOW_REUSE_WARNING_MESSAGE, DeprecationWarning)

File ~/anaconda3/envs/vt/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py:228, in root_validator(pre, skip_on_failure, allow_reuse, *__args)
    226 mode: Literal['before', 'after'] = 'before' if pre is True else 'after'
    227 if pre is False and skip_on_failure is not True:
--> 228     raise PydanticUserError(
    229         'If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`.'
    230         ' Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.',
    231         code='root-validator-pre-skip',
    232     )
    234 wrap = partial(_decorators_v1.make_v1_generic_root_validator, pre=pre)
    236 def dec(f: Callable[..., Any] | classmethod[Any, Any, Any] | staticmethod[Any, Any]) -> Any:

PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip

**Comment by AbrahamYelack** [comment]
I'm having the same issue, I've tried to remove the set_api_key() and include it in the request although I receive the same error. Tried v0.2.17 and prior but still the same error.

**Comment by CodeCraftPlugin** [comment]
Same i received the same error

**Comment by CodeCraftPlugin** [comment]
after installing eleven labs run this command ```pip install "pydantic==1.*"```

**Comment by TumblerWarren** [comment]
It worked thanks!

**Comment by flavioschneider** [comment]
This has been fixed in `v0.2.19`, the default pydantic version installed is `<2.0`.
