### ISSUE TITLE
TypeError in error.py

### ISSUE THREAD

**Issue by RJsam3** [elevenlabs/elevenlabs-python#54]
In the HTTPError class init function, I am getting:
`TypeError: list indices must be integers or slices, not str`
This happens because the first line of the function is: `detail = json.loads(response.text)["detail"]` 
This is returning a list and NOT a dict. The dict is the first index of the list.

Additionally, in the same function, it tries to set the variables self.message and self.status to detail["message"] and detail["status"}, but those keys do NOT exist. The key that I think self.message needs is actually "msg", and there is NO key for the self.status variable.

 Also, in the final line of the init function, `self.additional_info = detail.get("additional_info", None)`, is being called on the list, not the dict it is expecting, which is the first index of the list.

**Comment by felivalencia3** [comment]
Would you suggest something like this then:
1. The HTTPError class gets the dict from the first index of the list returned by json.loads(response.text) instead of assuming it is a dict.
2. The HTTPError class uses detail.get(“msg”, “Unknown error”) instead of detail[“message”] to get the error message, and detail.get(“status”, 0) instead of detail[“status”] to get the status code, with default values in case they are missing.

`import json
from typing import Dict, Optional

import requests  # type: ignore


class HTTPError(Exception):
    status: str
    message: str
    additional_info: Optional[Dict] = None

    def __init__(self, response: requests.Response):
        # Get the dict from the first index of the list
        detail = json.loads(response.text)[0]
        # Use "msg" instead of "message" and set a default value for status
        self.message = detail.get("msg", "Unknown error")
        self.status = detail.get("status", 0)
        # Pass the dict to the get method
        self.additional_info = detail.get("additional_info", None)
        super().__init__(self.message)


class APIError(HTTPError):
    message: Optional[str] = None

    def __init__(self, http_error: HTTPError):
        self.message = self.message or http_error.message
        self.http_error = http_error
        super().__init__(http_error.response)


class AuthorizationError(APIError):
    message: str = "This endpoint requires a valid API key, but none was found."


class RateLimitError(APIError):
    pass


class UnauthenticatedRateLimitError(RateLimitError):
    message: str = (
        "Thanks for trying out our speech synthesis! You have reached the limit of"
        " unauthenticated requests. You can continue, for free, by setting a valid API"
        " key."
    )
`

**Comment by RJsam3** [comment]
the original issue in error.py is located on line 14 inside the HTTPError class, inside the init function:

`def __init__(self, response: requests.Response):
        detail = json.loads(response.text)["detail"]
        self.message = detail["message"] ###Original error here, detail is expected to be a dict, but it is actually a list.
        self.status = detail["status"]
        self.additional_info = detail.get("additional_info", None)`

**Comment by flavioschneider** [comment]
I meant which kind of API request raises that wrong error, other requests return a dict as expected

**Comment by RJsam3** [comment]
Ah, my bad. I don't have the code anymore, but it was a `generate()` that did not have the correct api key (or no api key) followed by `play()`. All values were correct, but the api key was not set correctly.

**Comment by flavioschneider** [comment]
This should be fixed in `v0.2.25`
