### ISSUE TITLE
Error message shows a wrong char limit for users who are not logged in

### ISSUE THREAD

**Issue by Oleg-A-LLIto** [elevenlabs/elevenlabs-python#55]
![image](https://github.com/elevenlabs/elevenlabs-python/assets/43452849/98ace9cf-b4b0-4e49-98fc-c36a78d74b04)

**Comment by flavioschneider** [comment]
This is the limit for the request, not for the user

**Comment by Oleg-A-LLIto** [comment]
> This is the limit for the request, not for the user

It's PER request FOR users that are not signed in (did not provide API keys). The right limit per request, as I was told, is 333 characters. Regardless, this is clearly a bug, given it literally says "1640 > 2500" in the error message

**Comment by flavioschneider** [comment]
Yep, you're right, missed that. Can you provide the code to reproduce the error?

**Comment by Oleg-A-LLIto** [comment]
The following code does it for me:
`from elevenlabs import generate
generate(text='a'*400, model='eleven_monolingual_v1')
`
