### ISSUE TITLE
ffplay from ffmpeg not found, necessary to play audio

### ISSUE THREAD

**Issue by arcb01** [elevenlabs/elevenlabs-python#56]
Hello,

I ran into this issue `ffplay from ffmpeg not found, necessary to play audio` when trying to run the sample code from the README file. I am using Windows 10 and ffmpeg is installed (It is also added in system variables) and works fine when calling it in cmd. 

Any clue why this happens?

Thanks

**Comment by flavioschneider** [comment]
If you're using a virtual environment you might not have ffmpeg in the path

```py
Try adding

import os
os.environ['PATH'] += os.pathsep + '/path/to/ffmpeg/bin/'
```

**Comment by marcboggs** [comment]
I got around this by overriding the play() arguments

`def speak(text):
    audio = client.generate(
        text=text,
        voice="Matilda",
    )
    play(audio, notebook=False, use_ffmpeg=False)`
