### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by DandyDrop** [elevenlabs/elevenlabs-python#6]
I didnt understand how I can handle "Your quota is exceeded or your API key is invalid, please set a valid key: ELEVEN_API_KEY" error. It seems like this library does not include any Exception classes. I would be greatly thankful for the update or some explanation. And yeah, appreciate your work a lot.

**Comment by flavioschneider** [comment]
You can set your API key as:
```py
from elevenlabs import set_api_key

set_api_key("YOUR_API_KEY_HERE")
```

Check the bottom of the readme for more details: https://github.com/elevenlabs/elevenlabs-python#-api-key

**Comment by DandyDrop** [comment]
> You can set your API key as:
> 
> ```python
> from elevenlabs import set_api_key
> 
> set_api_key("<YOUR_API_KEY>")
> ```
> 
> Check the bottom of the readme for more details: https://github.com/elevenlabs/elevenlabs-python#-api-key

Okay, I do know this, but I`m running to this error because my quota has exceeded. So how can I catch the moment when I cant use my api key anymore this month using this library?

**Comment by flavioschneider** [comment]
I apologise for the misunderstanding. In `v0.2.7` you'll find a more proper error handling that raises a `RateLimitError` when quota for the current API key is exahusted. Similarly there's a more specific subclass of `RateLimitError` 
 called `UnauthenticatedRateLimitError` for unauthenticated users. 

```py
from elevenlabs import RateLimitError, UnauthenticatedRateLimitError
```

**Comment by DandyDrop** [comment]
Thank you, this works. ❣ Will continue on exploring this library and using your impressive service`s features, as well as trying to help at least a bit

**Comment by idarevalos** [comment]
Hello,
Have this error using eleventlabs

  File "/var/www/html/projects/dd-MyProject/api/wsgi.py", line 106, in audioGeneration
    audio = generate(
TypeError: generate() got an unexpected keyword argument 'model'
^C(.env) root@idarevalos-G7:/var/www/html/projects/dd-MyProject//api# 

How to resolve ?
Someone can help me ? 

python version 3.10.12
Name: elevenlabs, Version: 0.2.0
---
Thank you
