### ISSUE TITLE
latency parameter is missing

### ISSUE THREAD

**Issue by fylls** [elevenlabs/elevenlabs-python#62]
hey there, this is missing from the wrapper
https://help.elevenlabs.io/hc/en-us/articles/15726761640721-Can-I-reduce-API-latency-

**Comment by fylls** [comment]
hey there i created a pull request here: https://github.com/elevenlabs/elevenlabs-python/pull/63

**Comment by flavioschneider** [comment]
You can find the update in `v0.2.20`
