### ISSUE TITLE
Cuts off beginning of Audio

### ISSUE THREAD

**Issue by tigershark224** [elevenlabs/elevenlabs-python#66]
Hi! I am doing just the basic audio generation to a stream and the audio always cuts off the first word or so of the text. So if I say "Hi! this is bob, welcome to the airport," it does not produce audio for "hi!"

this is the code I'm using:

from elevenlabs import generate, stream
audio = generate(
				text = "Hi! this is bob, welcome to the airport",
				voice = "Bella",
				model = "eleven_monolingual_v1",
				stream = True
			)

stream(audio)

**Comment by flavioschneider** [comment]
Do you hear the first chunk when doing:

```py
from elevenlabs import generate, play

stream = generate(
  text = "Hi! this is bob, welcome to the airport",
  voice = "Bella",
  model = "eleven_monolingual_v1",
  stream = True
)

play(next(stream))
```

If that's the case there might be some some problem with MPV.
