### ISSUE TITLE
async support?

### ISSUE THREAD

**Issue by bryanhpchiang** [elevenlabs/elevenlabs-python#67]
for real-time applications / things with an ongoing event loop.

the TTS generate + streaming calls are both IO bound so it seems like this would make sense

**Comment by marty-sullivan** [comment]
Yes, would be great to use this official library, but we cannot use this on a web server because it has no async methods.

**Comment by amitkot** [comment]
@flavioschneider does providing asyncio python support currently on your roadmap?
We would appreciate un update 🙏

**Comment by dsinghvi** [comment]
@bryanhpchiang ElevenLabs just published a beta v3 SDK that you can download [here](https://github.com/elevenlabs/elevenlabs-python?tab=readme-ov-file#%EF%B8%8F-install). The SDK now exports a sync and async client!
