### ISSUE TITLE
Trailing spaces in several voice names

### ISSUE THREAD

**Issue by crcdng** [elevenlabs/elevenlabs-python#68]
There are trailing spaces in several voice names which causes the Python API to fail generating them:

- "Harry " instead of "Harry"
- "Matilda " instead of "Matilda"
- "Michael " instead of "Michael"
- "Mimi " instead of "Mimi"
- "Ryan " instead of "Ryan"

(I would recommend to add this to the unit tests)

**Comment by dunky11** [comment]
thanks! His should be fixed now.
