### ISSUE TITLE
How to select a language now with the Eleven Multilingual v1

### ISSUE THREAD

**Issue by kevngzc** [elevenlabs/elevenlabs-python#7]
Hello, 

is it possible now to select the language like in the UI with the new Eleven Multilingual v1 by the API with your python library ?

Regards,

<img width="519" alt="Screenshot 2023-04-30 at 18 42 27" src="https://user-images.githubusercontent.com/21306806/235365251-87f13fbd-b5f6-4c20-aacb-856ade248a11.png">

**Comment by flavioschneider** [comment]
Hi! This has been added to the python api in `v0.2.8` (`pip install elevenlabs -U`). You can use it as follows:

```py
from elevenlabs import generate, play

audio = generate(
    text="¡Hola! Mi nombre es Arnold, encantado de conocerte!",
    voice="Arnold",
    model='eleven_multilingual_v1'
)

play(audio)
```
