### ISSUE TITLE
API Error problem

### ISSUE THREAD

**Issue by LuckyGenius12** [elevenlabs/elevenlabs-python#71]
I having a huge problem with using Google Colab. It gets me a error saying "ErrorAPI"

"APIError                                  Traceback (most recent call last)
[<ipython-input-15-ec8ac870c202>](https://localhost:8080/#) in <cell line: 5>()
      3 # set_api_key
      4 
----> 5 voice = clone(
      6   text="Hi! My name is Olie, nice to meet you!",
      7   name="Olie",

3 frames
[/usr/local/lib/python3.10/dist-packages/elevenlabs/api/base.py](https://localhost:8080/#) in request(url, method, api_key, **kwargs)
     55                 raise AuthorizationError(error)
     56 
---> 57         raise APIError(error)
     58 
     59     @staticmethod

APIError: Invalid API key: '<YOUR_API_KEY>'"

Can you help me fix this?

**Comment by flavioschneider** [comment]
Looks like the API key you're using is invalid, please have a look at https://github.com/elevenlabs/elevenlabs-python#-api-key to get a valid API key.

**Comment by LuckyGenius12** [comment]
Where is valid API key?
