### ISSUE TITLE
Is there a way to set a specific language?

### ISSUE THREAD

**Issue by DevEsquilo** [elevenlabs/elevenlabs-python#72]
I'm pretty new to programming so api-references still confuses me.

I'm trying to use eleven_monolingual_v1 with some text in Portuguese, but the audio is always in Spanish.

Is there a way to set the language to Portuguese or another language?

**Comment by dunky11** [comment]
eleven_monolingual_v1 only supports English language as input, you have to use eleven_multlingual_v1 which supports English, German, Polish, Spanish, Italian, French, Portuguese and Hindi. You dont have to give any language identifier input to the API, we will select the correct language based on your text input automatically.

**Comment by DevEsquilo** [comment]
oof, my bad. 

I'm trying to achieve Bella's voice with stability 0.3 and smililarity 0.8 and eleven_multlingual_v1, in portuguese in specific.

I'm trying these two methods.
This first one generates a file with zero lenght when changed model_id to eleven_multlingual_v1, is there a way to these work with eleven_multlingual_v1 or is it capped with only mono?

`import requests

CHUNK_SIZE = 1024
url = "https://api.elevenlabs.io/v1/text-to-speech/EXAVITQu4vr4xnSDxMaL"

headers = {
  "Accept": "audio/mpeg",
  "Content-Type": "application/json",
  "xi-api-key": "abe8ef3c3701838b4963e03e80f7efba"
}

data = {
  "text": "eu me chamo diva, sou linda e poderosa, uma esquila genial. pega no meu pau",
  "model_id": "eleven_multlingual_v1",
  "voice_settings": {
    "stability": 0.5,
    "similarity_boost": 0.5
  }
}

response = requests.post(url, json=data, headers=headers)
with open('output.mp3', 'wb') as f:
    for chunk in response.iter_content(chunk_size=CHUNK_SIZE):
        if chunk:
            f.write(chunk)`


And for the second, it doesn't generate files, which is better for me.

It works great but I need stability and similarity, I had a look at "generate()" but it doesn't use api-key nor these voice settings, is there no way to use the voice settings here?


`import sys
from elevenlabs import generate, play

audio = generate(
    text="eu me chamo diva, sou linda e poderosa, uma esquila genial.",
    voice="Bella",
    model='eleven_multilingual_v1'
)

play(audio)`

**Comment by DevEsquilo** [comment]
After some time of rest and coffe, I could make this work, I was just being dumb

```
import sys
from elevenlabs import *
 
args = sys.argv[1:]

# Verifica o número de argumentos
if len(args) >= 3:
    texto = ' '.join(args)
else:
    texto = f"""Nada digitado"""

print(texto)

my_voice = VOICES_CACHE[2]
my_voice.settings.stability = 0.3
my_voice.settings.similarity_boost = 0.79

apikey= ""

audio = generate(texto, apikey ,voice=my_voice, model="eleven_multilingual_v1")
play(audio)
```
