### ISSUE TITLE
Generated audio volume declines towards end of speech

### ISSUE THREAD

**Issue by Zafirmk** [elevenlabs/elevenlabs-python#8]
When using the API to generate an audio of long text - the volume of the speaker declines towards the end.

To reproduce:
```python3
import requests

CHUNK_SIZE = 1024
url = "https://api.elevenlabs.io/v1/text-to-speech/MF3mGyEYCl7XYWbV9V6O"

headers = {
  "Accept": "audio/mpeg",
  "Content-Type": "application/json",
  "xi-api-key": [API KEY HERE]
}

data = {
  "text": "China's manufacturing activity unexpectedly shrank in April, according to official data, raising pressure on policymakers seeking to boost an economy struggling for a post-COVID lift-off amid subdued global demand and persistent property weakness. The official manufacturing purchasing managers' index (PMI) declined to 49.2 from 51.9 in March, below the 50-point mark that separates expansion and contraction in activity on a monthly basis. The world's second-biggest economy grew faster than expected in the first quarter thanks to robust services consumption, but factory output has lagged amid weak global growth.",
  "voice_settings": {
    "stability": 0.75,
    "similarity_boost": 0.75
  }
}

response = requests.post(url, json=data, headers=headers)
with open('output.mp3', 'wb') as f:
    for chunk in response.iter_content(chunk_size=CHUNK_SIZE):
        if chunk:
            f.write(chunk)
```
<img width="963" alt="Screenshot 2023-04-30 at 10 21 51 PM" src="https://user-images.githubusercontent.com/42074951/235392449-4b01859d-f47d-4487-8cdc-da44a81fefc4.png">

Link to generated audio: https://storage.googleapis.com/neutralnews-audio-bucket/output_1.mp3

**Comment by Zafirmk** [comment]
Not sure if this is an issue with this specific voice - but I can't try again with a different one because of the quotas on the API 😅

**Comment by ottsch** [comment]
Applying compression should help https://github.com/svpv/qadrc

**Comment by flavioschneider** [comment]
This might be an unlucky output. I cannot replicate on my end, but here's the output:

[audio.webm](https://user-images.githubusercontent.com/12028621/235912183-b7bf15d3-fca0-4a69-b124-37e6562b0164.webm)

**Comment by Zafirmk** [comment]
Ran into this issue repeatedly when working on a project - this [episode](https://open.spotify.com/episode/5RBaj7sQxuPsYQXvKW4FcA?si=9ba3008a7f444b7a) shows the issue for each news segment I believe, so I can rule out an unlucky output i'm afraid 😟 Have you been able to consistently get the "correct" output using this voice id MF3mGyEYCl7XYWbV9V6O?

**Comment by adnanhassan23** [comment]
facing this issue in node js too

**Comment by nukes** [comment]
that is a very common phenomenon for auto-regressive text-to-speech model.

**Comment by dhowe** [comment]
having a similar problem, where certain voices are much louder than others... is there some way to normalize the (streaming) output

**Comment by Zafirmk** [comment]
You can use `normalize` from the PyDub library.

Something like this
```python
from pydub import AudioSegment
from pydub.effects import normalize

# This makes the audio louder
normalized_audio = normalize(AudioSegment.from_file("sample.mp3"), headroom=-2.0)
```

However, despite this I still encountered drop off in volume levels. Alternatively, what you could try is creating a new voice altogether on the eleven labs platform. I no longer experience this issue after creating a new voice on the platform.

**Comment by dhowe** [comment]
can `pydub` be used for the streaming case?

**Comment by MichaelKuz** [comment]
We've been experimenting with re-cloning our voices, normalizing, etc. and still consistently run into this issue. 

Has anyone had any more success in post-processing elevenlabs beyond the normalize function that @Zafirmk mentioned above?

**Comment by dunky11** [comment]
This is a common issue with our model that long text inputs can result in degraded speech, we are working on fixing this. There are two ways to combat this:

1. Increase stability in voice settings
2. Manually chunk text by sentence breaks yourself, there are some open source sentence tokenizers to do that for you in various languages, then send each sentence to our API and concatenate the resulted audio

Its also dependent on the voice you use, voices that are more cartoonic / emotional seem to suffer more from this issue than voices that are monotone.

**Comment by devbusca** [comment]
@dunky11 Hi, regarding your point #2, do you think it is profitable in terms of time?  For example an audio of 2-3 mins, takes a time of 10-15s to make, how much would it be if done that way and how well would it be heard?
