### ISSUE TITLE
Specify Langauge

### ISSUE THREAD

**Issue by Soykertje** [elevenlabs/elevenlabs-python#83]
Now that the Multilingual model supports more languages and some of them vary from one region to another i.e. English (USA), English (UK), English (Australia), English (Canada); how do I set the specific language that I want to use?

Since there's no such option in the `generate` function, I don't see a way to do it.

`def generate(
    text: Union[str, Iterator[str]],
    api_key: Optional[str] = None,
    voice: Union[str, Voice] = VOICES_CACHE[2],  # Bella
    model: Union[str, Model] = "eleven_monolingual_v1",
    stream: bool = False,
    latency: int = 1,
    stream_chunk_size: int = 2048,
) -> Union[bytes, Iterator[bytes]]:`

**Comment by gvariable** [comment]
I thought the `voice` parameter was responsible for selecting accents. You can pass either the name of the voice or a `Voice` instance of your choice. To determine the voice you want to use, you can utilize `Voices.from_api()` which provides a list of available voices, with `accent` as one of the keys.

**Comment by Soykertje** [comment]
@gvariable That has nothing to do with picking up which accent so use, indeed the function to get the voices uses that funcion (`Voices.from_api()`):

`def voices() -> Voices:`
`    """Lists all voices in the API, if authenticated for the current user"""`
`    api_key = get_api_key()`
`    global VOICES_CACHE`
`    VOICES_CACHE = Voices.from_api(api_key) if api_key else VOICES_CACHE`
`    return VOICES_CACHE`


And for testing, you can generate some audio with a pre-made voice, for example "Charlotte" and the accent will be similar to the UK accent, but if you choose another one, for example with the label "american" it will generate the audio with an USA accent, but it is like that because those voices were trained with specific accents.

So let's say that I train a new voice using my own voice and as my first language is Spanish, I choose to upload audios speaking in Spanish, I can generate an audio in English but I want to choose the accent to use.

**Comment by flavioschneider** [comment]
At the moment it's not possible to select a different accent, however you can try cloning your voice and the accent might be preserved. If you want a high quality voice clone you can look into our professional voice cloning https://elevenlabs.io/professional-voice-cloning

**Comment by Soykertje** [comment]
@flavioschneider Are you guys thinking on doing that in the future? I mean cloning a voice in any language and then at the generation choose the specific language to use and not automatically inferred by the text?

**Comment by ostwilkens** [comment]
This is an important feature for real-time use. For example:
User: "Hej på dig!" (swedish)
Eleven: "God dag, hur står det till?" (swedish)
User: "Vad är jordens diameter?" (swedish)
Eleven: "12742 km" (pronounced in english = jarring)

**Comment by flavioschneider** [comment]
We are aware of this issue, a temporary hack to fix this is to convert numbers into words in the desired language

**Comment by dsinghvi** [comment]
Closing this issue since this is not a Python SDK issue and a general API request for the ElevenLabs team.
