### ISSUE TITLE
More Multilingual Support 

### ISSUE THREAD

**Issue by fire17** [elevenlabs/elevenlabs-python#84]
Hi there, congrats on the streaming update ! :)

I would like to ask, what's your pipeline for adding new languages?
I'm not sure how much training that you need, but for my language for example, Hebrew, there are already a pretty flawless speech to text free solutions.

So one just needs a whole bunch of recordings, clean them up, transcribe them, and you got a dataset.
Let me know if you'd like help or data
I really need an Hebrew Text to Speech,
And in general we need a full global multilingual with an easy way to add new languages

Hope it's already in the oven, please let me know. 
Thanks a lot and all the best ! 🙏

**Comment by yunusdemir** [comment]
I think this is the place to vote for Hebrew: https://feedback.elevenlabs.io/suggestions/p/hebrew

**Comment by flavioschneider** [comment]
Hi there! The new `eleven_multilingual_v2` model we now supports 28 languages. Unfortunately, Hebrew is not there yet, but it might come in the future. Best for now is to vote for it in https://feedback.elevenlabs.io/suggestions/p/hebrew as Yunus suggested.

**Comment by fire17** [comment]
I'd like to point out one of the comment suggestion

    Hebrew text-to-speech. Israel is one of the best high tech countries don't have a good tts. This will allow ten's  of thousand of compenies to integrade with elvenlabs

Basically even though there are only 10 million global Hebrew speakers, (smallish audience globally) we're very technologically inclined and we have no good tts, so there's a real need and opportunity here. 

Also @flavioschneider I feel like my original question was not fully answered. I don't really want to wait for things, but rather push the envelope, and help this become reality faster. Would love to be able to contribute, and take this job on, hopefully with your support and guidance. Please let me know how to get involved 🙏 thanks a lot and all the best
