### ISSUE TITLE
Unable to login or Unable to create account

### ISSUE THREAD

**Issue by LuckyGenius12** [elevenlabs/elevenlabs-python#88]
I couldn't login or create a account because I was gonna get a free valid API key but I couldn't login or create account, is there any issue to fix this login or create a account?
![Screenshot 2023-08-16 220931](https://github.com/elevenlabs/elevenlabs-python/assets/141376155/2ed13cc9-b79c-4ed1-9555-ff32e1bd3e0c)
![Screenshot 2023-08-17 142056](https://github.com/elevenlabs/elevenlabs-python/assets/141376155/c4598673-d5d9-43a1-aa98-9d0f49b1b151)

**Comment by flavioschneider** [comment]
This might have been a temporary issue. Does this persist?
