### ISSUE TITLE
'generate_stream_input' for the Browser

### ISSUE THREAD

**Issue by enricoros** [elevenlabs/elevenlabs-python#89]
Hi, there's a significant issue with porting the `generate_stream_input` function from Python to JavaScript (TypeScript). I'm opening the issue here to make sure the API takes into consideration the needs of "the web" at large, and not only the python ecosystem.

Python establishes a WebSocket connection to stream up chunks of text and receive audio buffers, and the connection is opened by the following code:
![image](https://github.com/elevenlabs/elevenlabs-python/assets/32999/b644bcee-65d4-4565-9c2c-8a4d33e6f8b0)

However, the **[WebSockets API](https://websockets.spec.whatwg.org/) (browser) does not allow adding headers to the WebSocket request**.
 - Documented at length in the following thread: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api
 - Workarounds: no direct workarounds for XI at the moment unless we want to interpose a Python server, which is antithetical to the feature (minimize latency)

**Are there other ways to make this work?**

Suggestion: there are 3 places at the moment where data is passed: 1. Headers (key), 2. Query (model, voice), 3. Stream (BOS, data, etc). _Could the xi-api-key be passed to query parameters, for this call?_ 

There's a new feature I'm releasing in my AI web app (https://github.com/enricoros/big-agi) that desperately needs proper JavaScript support for streamed-text generation - it's all ported and done, but the "additional_headers" is a showstopper.

Thank you

**Comment by flavioschneider** [comment]
The API key can also be provided in the BOS, here's a short example in JS:

```js
<!DOCTYPE html>
<html>
    <head>
        <script>
            const apiKey = "<your-api-key>";
            const voiceId = "21m00Tcm4TlvDq8ikWAM";
            const modelId = "eleven_monolingual_v1";

            const url = `wss://api.elevenlabs.io/v1/text-to-speech/${voiceId}/stream-input?model_id=${modelId}`;
            const socket = new WebSocket(url);

            const BOS = JSON.stringify({
                text: " ",
                try_trigger_generation: true,
                generation_config: {
                    chunk_length_schedule: [50]
                },
                "xi-api-key": apiKey
            });
            const EOS = JSON.stringify({ text: "" });
            socket.addEventListener("open", (event) => {
                console.log("Connected to server");
                socket.send(BOS); 
                socket.send(JSON.stringify({ text: "Hello there! " }));
                socket.send(JSON.stringify({ text: "How are you doing? " }));
                socket.send(EOS); 
            });

            socket.addEventListener("message", (event) => {
                let audioData = JSON.parse(event.data).audio;
                console.log(audioData)
            });
        </script>
    </head>
</html>
```

**Comment by AbubakrChan** [comment]
> The API key can also be provided in the BOS, here's a short example in JS:
> 
> ```js
> <!DOCTYPE html>
> <html>
>     <head>
>         <script>
>             const apiKey = "<your-api-key>";
>             const voiceId = "21m00Tcm4TlvDq8ikWAM";
>             const modelId = "eleven_monolingual_v1";
> 
>             const url = `wss://api.elevenlabs.io/v1/text-to-speech/${voiceId}/stream-input?model_id=${modelId}`;
>             const socket = new WebSocket(url);
> 
>             const BOS = JSON.stringify({
>                 text: " ",
>                 try_trigger_generation: true,
>                 generation_config: {
>                     chunk_length_schedule: [50]
>                 },
>                 "xi-api-key": apiKey
>             });
>             const EOS = JSON.stringify({ text: "" });
>             socket.addEventListener("open", (event) => {
>                 console.log("Connected to server");
>                 socket.send(BOS); 
>                 socket.send(JSON.stringify({ text: "Hello there! " }));
>                 socket.send(JSON.stringify({ text: "How are you doing? " }));
>                 socket.send(EOS); 
>             });
> 
>             socket.addEventListener("message", (event) => {
>                 let audioData = JSON.parse(event.data).audio;
>                 console.log(audioData)
>             });
>         </script>
>     </head>
> </html>
> ```

Is this streaming the audio live or simply playing it?
