### ISSUE TITLE
Will you support wav audio format?

### ISSUE THREAD

**Issue by Jun711** [elevenlabs/elevenlabs-python#90]
I have tried the API and there doesn't seem to be an option for wav audio format.

I got a reply in discord that wav format is not currently being supported

**Comment by dunky11** [comment]
.wav files are supported using the API

**Comment by flavioschneider** [comment]
You can save the output to wav using the `save` function https://github.com/elevenlabs/elevenlabs-python/blob/main/API.md#save

**Comment by tagawa** [comment]
I think the linked documentation is wrong. Output files from this package start with hex `FF FB` which is a signature for MP3 files (without ID3 tags). Software such as VLC can still play the files even with a .wav extension, but their format is MP3.

**Comment by flavioschneider** [comment]
We don't plan on supporting wav export any time soon, you can request the feature here and it might be implemented if it gets enough votes: https://feedback.elevenlabs.io/suggestions

**Comment by shortcipher3** [comment]
```
# ffmpeg -i output.wav
```
Shows it is an mp3:
```
Input #0, mp3, from 'output.wav':
  Duration: 00:00:00.97, start: 0.000000, bitrate: 64 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
```

The feature has been suggested [here](https://feedback.elevenlabs.io/suggestions/p/more-audio-formats)

Looks like it would need a lot more votes to get traction, so add yours if you want this feature.

**Comment by shortcipher3** [comment]
The feature was suggested [here](https://feedback.elevenlabs.io/suggestions/p/allow-the-ability-to-download-the-file-in-wav-format) with more votes.
