### ISSUE TITLE
Streaming Functionality Broken?

### ISSUE THREAD

**Issue by Ushi-Oni** [elevenlabs/elevenlabs-python#98]
Hey all - big fan of your work at the labs!

It seems like the streaming functionality is broken - I've tried to use the examples _verbatim_ and the program just hangs indefinitely once it goes into the generate func. I tried doing some troubleshooting via procmon to see if anything weird was going on with MPV but I didn't see any errors/issues. I'm wondering if it has to do with the headless option as I think I recall having an issue with that in the past IIRC but have no clue. 

**Something to note, everything works as expected when not streaming the audio (both with streaming text input and with static text input) so I'm rather confident its with the streaming component specifically The elevenlabs library is at the most recent version (0.2.24), and I'm on windows _11_.**

Here's the code I'm running for completeness sake:

```
from elevenlabs import generate, set_api_key, stream, play
import keyring

def text_stream():
    yield "Hi there, I'm Eleven "
    yield "I'm a text to speech API "

def main():
    print('Setting API Key...')
    set_api_key(keyring.get_password('elevenlabs.io', 'n/a'))
    print('Done Setting API Key')

    print('Starting Audio Stream creation via Generate()...')
    audio_stream = generate(
        text=text_stream(),
        voice="Nicole",
        model="eleven_monolingual_v1",
        stream=True,
    )
    print('Completed Audio Stream Initial creation via Generate()')

    print('Begin Streaming...')
    stream(audio_stream)
    print('Done Streaming')

    exit(0)

if __name__ == '__main__':
    main()
```

I'm willing to bet you have some deadlocking occurring within the code somewhere.

EDIT: I forgot to mention that I don't believe the requests are even making it to the server as the prompts don't end up showing in my history.

**Comment by jay2jp** [comment]
I believe its because you left the voice as Nicole and not the voice Id you need

**Comment by flavioschneider** [comment]
This might be an issue with MPV on windows, does simply printing the output work? 

```py
...
for chunk in audio_stream:
   print(chunk)
```

**Comment by Ushi-Oni** [comment]
Yep works fine, returns the binary string. Was something recently changed with how MP3 files are returned? Seems like alternatives that were working for streaming audio are now non-functional. I would normally open a new issue but figure this is an appropriate place for this tid bit of info to be shared and aggregated. Thanks

**Comment by MohammadHomsee** [comment]
It seems like it's loading all chunks first then go through the loop, 
`for chunk in audio_stream:`
`   print(chunk)`

streaming is broken! even though I have set streaming to true
