### ISSUE TITLE
Help with Langchain integration

### ISSUE THREAD

**Issue by ChristianEvc** [elevenlabs/elevenlabs-python#99]
Hi all, 

I'm trying out the new streaming feature, and it works fine with the recomended implementation for me (I'm on an M2 mac), so the following works (I've omitted the import statements and such).

```
def write(prompt: str):
    for chunk in openai.ChatCompletion.create(
        model = "gpt-4",
        messages = [{"role":"user","content": prompt}],
        stream=True,
    ):
        content = chunk["choices"][0].get("delta", {}).get("content")
        if content is not None:
            yield content
            print("ContentTester:", content)

planet = "Tell me about mars"
audio_stream = elevenlabs.generate(
    text=write(planet),
    voice="Adam",
    stream=True,
    latency=3,  
)
```

However, I want to get this to work via Langchain chains instead, so for example setting up a ConversationChain with memory, and have the output stream to Elevenlabs just like it does in this example. I think the right way to do this is using Callbacks, but for the life of me I cannot figure out how to make the words stream to the Elevenlabs API. It always waits untill the Chain has finished responding. Here is an example of my code (that doesn't work):

```
class MyCustomHandler(BaseCallbackHandler):
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        yield token
```

If anyone has any ideas, any help is greatly appreciated!

**Comment by Ushi-Oni** [comment]
It seems this may be dead lock issue with the stream function, the code is essentially an unprotected write to stdin and then a flush after to the mpv process. It seems for me that it locks up during the flush operation when running my debugger. (I am on win11 however but I believe this to be async. with your OS)

**Comment by ChristianEvc** [comment]
Hey @Ushi-Oni. Thanks for your reply. It makes sense that that is whats happening. Any ideas how to resolve? I've tried to make the callback async, and calling the function asyncronously as well, but I don't believe I'm doing it correctly. I'll post a few examples when I'm back at a computer

**Comment by Ushi-Oni** [comment]
@ChristianEvc No problem, and I'm not 100% sure. The old elevenlabs library (unofficial) has a stream function which works perfectly for me on windows. It's likely just that there needs to be safer writing and flushing processes in the stream function itself. I'm not 100% sure however so I'll be taking a peak at their code in a bit, hopefully will be able to glean some insights and update my issue
